### ISSUE TITLE
Type override not works with "integer", "int", "int4"

### ISSUE THREAD

**Issue by sadicann** [kyleconroy/sqlc#1005]
It seems that a type override not working for "integer", "int" and "int4" database types. Just "pg_catalog.int" type is working for integers.

It's not working. 
```
overrides:
  - go_type:
      import: "gopkg.in/guregu/null.v4"
      package: "null"
      type: "Int"
    db_type: "int"
    nullable: true
```

But it's working:
```
overrides:
  - go_type:
      import: "gopkg.in/guregu/null.v4"
      package: "null"
      type: "Int"
    db_type: "pg_catalog.int"
    nullable: true
```
