### ISSUE TITLE
Override for interval type

### ISSUE THREAD

**Issue by tschaub** [kyleconroy/sqlc#1023]
It looks like #601 added support for the `interval` type and that the corresponding go type is `int64`.  I'm guessing this means intervals will be converted into a number of microseconds.

I'm hoping to be able to retain more information from the interval – to retain an integer number of months, for example.  I tried adding the following override to my `sqlc.yaml` (as suggested in https://github.com/kyleconroy/sqlc/issues/429#issuecomment-607930265):
```yaml
overrides:
  - db_type: "interval"
    go_type: "github.com/jackc/pgtype.Interval"
  - db_type: "interval"
    go_type: "github.com/jackc/pgtype.NullInterval"
    nullable: true
```

With this override, the resulting struct still has an `int64` type field.  Is there a way to override "built in" types, or are overrides just for unknown types?

I'm using v1.8.0.

**Comment by tschaub** [comment]
I just discovered that using `pg_catalog.interval` for the `db_type` in the override does the trick:

```yml
overrides:
  - db_type: "pg_catalog.interval"
    go_type: "github.com/jackc/pgtype.Interval"
  - db_type: "pg_catalog.interval"
    go_type: "github.com/jackc/pgtype.NullInterval"
    nullable: true
```

It looks like this ticket is more or less a duplicate of #922 and #1005 (and maybe #814 and perhaps #950), so I'll close.
