### ISSUE TITLE
numeric type broken by default with pgx driver

### ISSUE THREAD

**Issue by jvatic** [kyleconroy/sqlc#1067]
Attempting to query a column of type `numeric` fails with `can't scan into dest[1]: unable to assign to *string` when using the pgx driver.

```yaml
# sqlc.yaml
version: "1"
packages:
  - engine: "postgresql"
    driver: "pgx/v4"
```

Overriding the type fixes the error:

```yaml
# sqlc.yaml
# ...
overrides:
  - db_type: "pg_catalog.numeric"
    go_type: "float64" # change to a proper decimal type, e.g. github.com/shopspring/decimal.Decimal
```

Using `lib/pq` instead of pgx works as expected using the default `go_type` of `string` without having to add the type override.
