### ISSUE TITLE
NULLIF

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#1154]
### Version

1.9.0

### What happened?

A bug happened!

### Database schema

```sql
CREATE TABLE author (
  id bigserial NOT NULL
);
```

### SQL queries

```sql
-- name: GetRestrictedId :one
SELECT
  NULLIF(id, $1) restricted_id
FROM
  author;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "engine": "postgresql",
      "path": "go",
      "name": "querytest",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/321eb83b945edfab5a41d8c91feb596bcab9860ce1780639d1f9863207a20644

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
