### ISSUE TITLE
Timediff comparison

### ISSUE THREAD

**Issue by huyennbl** [kyleconroy/sqlc#1172]
### Version

1.8.0

### What happened?

I'm not sure if it's a bug or I'm doing this thing in the wrong way

I expect `expDuration` to be a string type so the query would look like 

```
UPDATE foo
SET used_at = CURRENT_TIMESTAMP
WHERE TimeDiff(CURRENT_TIMESTAMP,created_at) < "00:15:00"
```
So I tried to add `::string` or `::text` after the `sqlc.arg(expDuration)` but neither work. It shows syntax error.
How can input the duration of 15 minutes with the type `time.Time` that sqlc generated for me?

### SQL queries

```sql
-- name: UseToken :execresult
UPDATE foo
SET used_at = CURRENT_TIMESTAMP
WHERE TimeDiff(CURRENT_TIMESTAMP,created_at) < sqlc.arg(expDuration)
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "mysql"
    emit_interface: false
    emit_prepared_queries: false
    emit_exact_table_names: false
    emit_empty_slices: true
```

### What operating system are you using?

Windows

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
