### ISSUE TITLE
Incorrect code generation

### ISSUE THREAD

**Issue by lpintes** [kyleconroy/sqlc#1175]
This is my very first experience with this tool, so I created a toy example to familiarize myself how it works.

The query code it generates is incorrect, a parameter is missing, only context is provided. Tool generates everything without errors.

```sql
create table Players (
  PlayerId int primary key auto_increment,
  Name varchar(25) unique not null,
  Email varchar(254) unique not null
);

-- name: FindPlayerById :one
select * from Players where PlayerId = $1;

-- name: FindPlayerByEmail :one
select * from Players where Email = $1;
```

```yaml
version: 1
packages:
  - path: "tutorial"
    name: "tutorial"
    engine: "mysql"
    schema: "schema.sql"
    queries: "query.sql"
```
