### ISSUE TITLE
overwrite of uuid package is not working correctly starting from v1.10 

### ISSUE THREAD

**Issue by MoritzGruber** [kyleconroy/sqlc#1186]
### Version

1.10.0

### What happened?

Hello,
first of all, thanks for building this amazing library! 

I just noticed while upgrading from v 1.9.0 to v1.10 that the overwrite:

sqlc.yaml:
```
version: "1"
packages:
     ...
    overrides:
      - go_type: "github.com/gofrs/uuid.UUID"
        db_type: "uuid"
```

i get this generated output in v1.10.0

```
import (
        ...
	"github.com/gofrs/uuid"
	"github.com/google/uuid"
)
```
which was just "github.com/gofrs/uuid" before in v1.9.0

### Configuration

```yaml
version: "1"
packages:
  - name: "sqlgen"
    path: "./pkg/storage/sqlgen"
    queries: "./sql/queries/"
    schema: "./sql/migrations/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: true
    emit_exported_queries: true
    emit_interface: true
    emit_exact_table_names: false
    emit_empty_slices: true
    overrides:
      - go_type: "github.com/gofrs/uuid.UUID"
        db_type: "uuid"

rename:
  UserId: "UserID"
  organization_id: "project_id"
  organizationId: "ProjectID"
  OrganizationId: "ProjectID"
  schema_field: "BlueprintField"
  schemaField: "BlueprintField"
  Variant: "Type"
  Schema: "Blueprint"
  schema: "Blueprint"
  schemaId: "BlueprintID"
  SchemaID: "BlueprintID"
  SchemaId: "BlueprintID"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Thanks for the bug report. I opened a new issue to track the duplicate import issue [here](https://github.com/kyleconroy/sqlc/issues/1190). I wanted to make sure I had a full reproduction of the issue.

You can fix the issue now by also overriding nullable UUIDs.

```yaml
version: "1"
packages:
     ...
    overrides:
      - go_type: "github.com/gofrs/uuid.UUID"
        db_type: "uuid"
      - go_type: "github.com/gofrs/uuid.UUID"
        db_type: "uuid"
        nullable: true
```
