### ISSUE TITLE
Missing binds in ORDER BY

### ISSUE THREAD

**Issue by jamisonhyatt** [kyleconroy/sqlc#1194]
### Version

1.10.0

### What happened?

:wave:  Experimenting with sqlc and conditional order by's aren't generating the code for `mysql` as I'd expect.  Didn't see any matching issues - hopefully I didn't miss one.

As you can see by the example below, the mysql generated code skips the `sqlc.arg(sort_column)` bind.

As an alternate example, here's postgres [working as expected](https://play.sqlc.dev/p/63584f276cb2b1a163d6f4e83bbf19b667bfd38010fbcfb07fccf29371b97e4c)

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGINT PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT * FROM authors
WHERE id > sqlc.arg(min_id) 
ORDER BY CASE WHEN sqlc.arg(sort_column) = 'name' THEN name END;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/4d6a51438a52ec0067279884c6327f14e1c2e50d3057591178c44e438f926385

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
