### ISSUE TITLE
`INSERT` query with `RETURNING *` does not implement `RETURNING *`

### ISSUE THREAD

**Issue by brunoluiz** [kyleconroy/sqlc#1212]
### Version

1.10.0

### What happened?

When doing insert/upsert queries with `RETURNING *` statement + `:exec`, it seems `sqlc` is not mapping the query result. In such a case, are we expected to use `:one` or is this an actual issue?

### Relevant log output

```shell
// not the log output, but the generated code

const createAccount = `-- name: CreateAccount :exec
INSERT INTO accounts (
  id, name
) VALUES (
  $1, $2
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name
RETURNING id, name
`

type CreateAccountParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) error {
	_, err := q.db.ExecContext(ctx, createAccount, arg.ID, arg.Name)
	return err
}
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS accounts (
    id UUID primary key,
    name text not null
);
```

### SQL queries

```sql
-- name: CreateAccount :exec
INSERT INTO accounts (
  id, name
) VALUES (
  $1, $2
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name
RETURNING *;
```

### Configuration

```yaml
version: 1
packages:
  - name: "store"
    emit_json_tags: true
    emit_interface: true
    path: "./internal/store"
    engine: "postgresql"
    schema: "./internal/store/migrations"
    queries: "./internal/store/query.sql"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
