### ISSUE TITLE
mysql syntax error near "TRIGGER x"

### ISSUE THREAD

**Issue by tiehm** [kyleconroy/sqlc#1214]
### Version

1.10.0

### What happened?

The following code errors with `syntax error near "TRIGGER [trigger name]"`

### Relevant log output

```shell
sql/schema/notificationQueue.sql:21:15: syntax error near "trigger if not exists notification_queue_done"
```

### Database schema

```sql
create table notification_queue
(
    id             bigint auto_increment
        primary key,
    state          ENUM('waiting', 'in-progress', 'errored', 'done')                           not null,
    finished_at    datetime null
);

create trigger notification_queue_done
    after update
    on notification_queue
    for each row
begin
    if old.state != 'done' and new.state = 'done' then
        update notification_queue set finished_at = now() where id = old.id;
    end if;
end;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "name": "db",
      "path": "internal/db",
      "engine": "mysql",
      "queries": "./sql/query/",
      "schema": "./sql/schema/",
      "json_tags_case_style": "snake",
      "emit_json_tags": true
    }
  ],
  "overrides": [
    {
      "db_type": "string",
      "go_type": {
        "import": "gopkg.in/guregu/null.v4",
        "package": "null",
        "type": "String"
      },
      "nullable": true
    },
    {
      "db_type": "text",
      "go_type": {
        "import": "gopkg.in/guregu/null.v4",
        "package": "null",
        "type": "String"
      },
      "nullable": true
    },
    {
      "db_type": "datetime",
      "go_type": {
        "import": "gopkg.in/guregu/null.v4",
        "package": "null",
        "type": "Time"
      },
      "nullable": true
    },
    {
      "db_type": "timestamp",
      "go_type": {
        "import": "gopkg.in/guregu/null.v4",
        "package": "null",
        "type": "Time"
      },
      "nullable": true
    },
    {
      "db_type": "int",
      "go_type": {
        "import": "gopkg.in/guregu/null.v4",
        "package": "null",
        "type": "Int"
      },
      "nullable": true
    },
    {
      "db_type": "float",
      "go_type": {
        "import": "gopkg.in/guregu/null.v4",
        "package": "null",
        "type": "Float"
      },
      "nullable": true
    }
  ]
}
```

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
