### ISSUE TITLE
Column matching is case sensitive

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#1215]
### Version

1.10.0

### What happened?

`sqlc generate` fails to find a column if it's specified with a different case. 

### Relevant log output

```shell
sqlc generate failed.

# package db
query.sql:8:1: column "nAmE" does not exist
query.sql:16:1: column "nAmE" does not exist
query.sql:23:1: column "nAmE" does not exist
```

### Database schema

```sql
CREATE TABLE authors (
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE nAmE = ? LIMIT 1;

-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY nAmE;

-- name: CreateAuthor :exec
INSERT INTO authors (
  nAmE, bIo
) VALUES (
  ?, ?
);

-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE nAmE = ?;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/9d9c5b593d84731685a8854d035b53306f5bf083dc5a8857af44d6da1679ca51

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
