### ISSUE TITLE
Cockroachdb `INDEX` definitions can produce invalid queries

### ISSUE THREAD

**Issue by nickjackson** [kyleconroy/sqlc#1221]
### Version

1.10.0

### What happened?

I am fully aware cockroachdb engine is not directly supported, but I wanted to report in case this could be fixed without needing direct cockroachdb support. For the most part `sqlc` with the postgres engine is working fine for me with my cockroachdb schema/queries. 

Cockroachdb allows for [index definitions](https://www.cockroachlabs.com/docs/stable/sql-grammar.html#index_def) within `CREATE TABLE` statements.

When trying to put a schema with an index through,`sqlc` assumes the INDEX is a column instead and when `SELECT *` or `RETURNING *` within a query, sqlc will incorrectly add "index" as a column to the query.

I know this is a long shot, and is probably out of scope at this time. I can always use `ALTER TABLE` to create indexes instead. Many thanks for your time.

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text,
  INDEX foo (id)
);
```

### SQL queries

```sql
SELECT * FROM authors
WHERE id = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/e5c40f87ff8da7f76bbbc4106712a1b85636de82fbb844111cf4ddfeca71d638

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
