### ISSUE TITLE
last rune is truncated if query.sql doesn't end with ; (mysql)

### ISSUE THREAD

**Issue by Funzinator** [kyleconroy/sqlc#1240]
### Version

1.10.0

### What happened?

Hi.

I just noticed a small issue when playing around with sqlc.
Using the example from the documentation (but forgetting the last `;`)
```sql
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name
```

will result in code generated like this:
```go
const listAuthors = `-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY nam
`
```

`sqlc generate` parses the file properly but resulting in wrong code. The easy fix is to add the `;` back but maybe it's better to show an error during `sqlc generate`?

I've also tried this with the current main branch. Happens there as well.

PS: Only happens in mysql mode. Postgres mode is rejecting the query.sql.

### Database schema

```sql
CREATE TABLE authors (
  id   BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name text    NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name
```

### Configuration

```yaml
version: 1
packages:
  - path: "tutorial"
    name: "tutorial"
    engine: "mysql"
    schema: "schema.sql"
    queries: "query.sql"
    emit_prepared_queries: true
```

### Playground URL

https://play.sqlc.dev/p/a1d7202b8184fb6896ff9e6366363473b8bbc92549738764a4012b5021d8c19d

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
