### ISSUE TITLE
Sqlite3: "duplicate query name" when there is no duplicate query name

### ISSUE THREAD

**Issue by StevenACoffman** [kyleconroy/sqlc#1260]
### Version

1.10.0

### What happened?

I know the sqlite3 (`_lemon`) engine is experimental, but when I run:
`sqlc-dev generate -x -f sqlc.yaml` (or `go run github.com/kyleconroy/sqlc/cmd/sqlc -x -f sqlc.yaml` in a directory with this config I get `queries/queries.sql:2:43: duplicate query name: GetProjects ` when there are not any duplicates. If I change the engine to `postgresql` I do not get those errors and things are generated fine.

I have commented out the SQL queries that are invalid in postgresql due to differing date functions. 

### Relevant log output

```shell
$ go generate ./...
# package jirasql
queries/queries.sql:2:43: duplicate query name: GetProjects
exit status 1
generate.go:4: running "go": exit status 1
```
### Database schema

[migrations.zip](https://github.com/kyleconroy/sqlc/files/7448008/migrations.zip)

### SQL queries

[queries.zip](https://github.com/kyleconroy/sqlc/files/7448007/queries.zip)

### Configuration

```yaml
sqlc.yaml:

version: "1"
packages:
  - name: "jirasql"
    path: "./generated/jirasql"
    queries: "queries"
    schema: "migrations"
    engine: "_lemon"
    #    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: true
    emit_exact_table_names: false
```

### Playground URL

https://play.sqlc.dev/p/adacccdabcc93fbd41aa3eaa3f74050b1b8701c3c69545de3c5c85079e413cec

### What operating system are you using?

macOS

### What database engines are you using?

SQLite (`_lemon`)

### What type of code are you generating?

Go
