### ISSUE TITLE
 Syntax error at or near "..."

### ISSUE THREAD

**Issue by F34th3R** [kyleconroy/sqlc#1287]
### Version

1.10.0

### What happened?

This is a similar error [issues 1007](https://github.com/kyleconroy/sqlc/issues/1007)
example:
```sql
...
ORDER BY U.id
LIMIT sqlc.arg(limit)
OFFSET sqlc.arg(offset);
```

the error message shows: `syntax error at or near the "limit"`

### Relevant log output

```shell
$ db/query/user.sql:1:1: syntax error at or near "limit"
```

### Database schema

```sql
CREATE TABLE "users" (
  "id" bigserial PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL,
  "name" varchar NOT NULL,
  "email" varchar NOT NULL,
  "role_id" bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "updated_at" timestamptz NOT NULL DEFAULT (now())
);
```

### SQL queries

```sql
select 
  U.id, 
  U.code,
  U.name,
  R.name as role,
  U.email,
  U.created_at,
  U.updated_at
from users U
inner join roles R
on U.role_id = R.id
WHERE R.id = sqlc.arg(role_id)
ORDER BY U.id
LIMIT sqlc.arg(_limit)
OFFSET sqlc.arg(_offset);
```

### Configuration

```yaml
version: 1
packages:
  - name: "db"
    path: "./db/sqlc/"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
