### ISSUE TITLE
emit_result_struct_pointers

### ISSUE THREAD

**Issue by FlymeDllVa** [kyleconroy/sqlc#1314]
### Version

1.11.0

### What happened?

error parsing sqlc.yaml: yaml: unmarshal errors:
  line 8: field emit_result_struct_pointers not found in type config.v1PackageSettings

### Relevant log output

```shell
sqlc generate
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 8: field emit_result_struct_pointers not found in type config.v1PackageSettings
```

### Configuration

```yaml
version: 1
packages:
  - name: "store"
    schema: "migrations"
    path: "internal/pkg/store"
    queries: "internal/pkg/store/queries"
    engine: "mysql"
    emit_result_struct_pointers: true
    emit_db_tags: true
    emit_json_tags: true
    json_tags_case_style: "camel"
    output_db_file_name: "store"
```

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
