### ISSUE TITLE
syntax error near "unix_timestamp(),"

### ISSUE THREAD

**Issue by markus-wa** [kyleconroy/sqlc#1374]
### Version

1.11.0

### What happened?

syntax error near "unix_timestamp(),"

mysql supports `DEFAULT unix_timestamp()` at table creation. I would expect sqlc to not crash :cry: 

### Relevant log output

```shell
# package db
query.sql:6:62: syntax error near "unix_timestamp(),"
```

### Database schema

```sql
CREATE TABLE `1v1_challenge_invite_logs` (
  `user_id` int(10) unsigned NOT NULL,
  `requester_user_id` int(10) unsigned NOT NULL,
  `status` tinyint(3) unsigned NOT NULL DEFAULT 0,
  `inserted` int(10) unsigned NOT NULL DEFAULT unix_timestamp(),
  `deleted` int(10) unsigned NOT NULL DEFAULT unix_timestamp(),
  KEY `user_id_requester_user_id` (`user_id`,`requester_user_id`),
  KEY `inserted` (`inserted`),
  KEY `requester_user_id` (`requester_user_id`),
  CONSTRAINT `1v1_challenge_invite_logs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `1v1_challenge_invite_logs_ibfk_2` FOREIGN KEY (`requester_user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
```


### SQL queries

```sql
n/a
```

### Configuration

```yaml
version: 1
packages:
  - path: "internal/dota2/matches/stats/statsdb"
    name: "statsdb"
    engine: "mysql"
    schema: "./schema.sql"
    queries: "query.sql"
```

### Playground URL

https://play.sqlc.dev/p/0c706ff71a9cb78349b75397ad2f12ac23f9cbd2051c66528047a447c281d5ce

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
