### ISSUE TITLE
Function call in FROM

### ISSUE THREAD

**Issue by odoland** [kyleconroy/sqlc#1381]
### Version

1.11.0

### What happened?

Support result sets in the FROM clause from function calls.
Ex, in Postgres:
`
SELECT temp.id
FROM UNNEST(...) AS temp(id)
` 
to be able to find the id

### Relevant log output

```shell
query.sql:101:8: column "file_name" does not exist
exit status 1
```
```


### Database schema

```sql
CREATE TABLE files (
  id   SERIAL PRIMARY KEY,
  name text NOT NULL
);
```

### SQL queries

```sql
-- name: GetMissingFileNames :many
SELECT temp.file_name
FROM unnest(@file_names::text[]) AS temp(file_name)
LEFT JOIN files on files.name = temp.file_name
WHERE files.id IS NULL;
```

### Configuration

```yaml
version: 1
packages:
  - path: "."
    name: "models"
    engine: "postgresql"
    schema: "schema.sql"
    queries: "query.sql"
```

### Playground URL

https://play.sqlc.dev/p/2283b61196ae7505572db4dca29075c6a7395781064710288b63b53602289c70

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
