### ISSUE TITLE
Subquery with count as alias compiles to interface{} type [MySQL Only]

### ISSUE THREAD

**Issue by HenkVanMaanen** [kyleconroy/sqlc#1383]
### Version

1.11.0

### What happened?

When compiling the subquery alias compiles to the interface{} type instead of int64. See playground: https://play.sqlc.dev/p/1f6e668fb3015032c9e28259e03ef5a8d0a045a543d6b367f23642c424116a44

Here is the example with postgres working just fine: https://play.sqlc.dev/p/460a9eedb3b1fa2649415cb09eeb9e7a30b8c35512ea47312e1fd8f12d58f2d5

### Database schema

```sql
create table one (
  id int primary key,
  otherfield varchar(255),
  name varchar(255)
);
```

### SQL queries

```sql
-- name: Test :many
select 
	otherfield, 
	(select COUNT(*) from one o where one.id = 5 limit 1) as cnt
from one;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
   ]
}
```

### Playground URL

https://play.sqlc.dev/p/1f6e668fb3015032c9e28259e03ef5a8d0a045a543d6b367f23642c424116a44

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
