### ISSUE TITLE
Primary key with ordering fails to compile

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#1390]
### Version

1.11.0

### What happened?

sqlc can't compiler a primary key with an ordering in PostgreSQL.

Originally reported by @danthegoodman1 in https://github.com/kyleconroy/sqlc/issues/1389

### Relevant log output

```shell
sqlc generate failed.

# package db
query.sql:1:1: syntax error at or near "DESC"
```

### Database schema

```sql
CREATE TABLE authors (
  one  BIGSERIAL,
  two  BIGSERIAL,
  PRIMARY KEY(player_id, id DESC)
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE one = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/2d2bfa801977bf65e134f44c34ee90d59a871d2c313d8e7c3e9593944272b3c8

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
