### ISSUE TITLE
Column with ON UPDATE clause fails to compile

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#1391]
### Version

1.11.0

### What happened?

When creating a table with ON UPDATE, sqlc fails to generate code.

Originally reported by @danthegoodman1 in #1389

### Relevant log output

```shell
sqlc generate failed.

# package db
query.sql:1:1: syntax error at or near "ON"
```

### Database schema

```sql
CREATE TABLE authors (
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW() ON UPDATE NOW()
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/fb16079971d464b07987a931f67501f4d94e490c3f653aff4d8dc4ee1f9bb797

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
