### ISSUE TITLE
Cannot set path to "sqlc" in sqlc.yaml

### ISSUE THREAD

**Issue by dclipca** [kyleconroy/sqlc#1423]
### Version

1.11.0

### What happened?

Unable to run ```./sqlc generate``` when path is equal to ```sqlc``` in ```sqlc.yaml````.
Not a big deal of course but I think it would be better if this would be noted somewhere.

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
Can you please include your full `sqlc.yaml` file? I'm not sure I 100% what's going on.

**Comment by dclipca** [comment]
> Can you please include your full `sqlc.yaml` file? I'm not sure I 100% what's going on.

```
version: 1
packages:
  - path: "sqlc"
    name: "sqlc"
    engine: "postgresql"
    schema: "schema.sql"
    queries: "query.sql"
    sql_package: "pgx/v4"
    emit_result_struct_pointers: true 
```
