### ISSUE TITLE
Can't use name parameters for less than/greater than conditions

### ISSUE THREAD

**Issue by danthegoodman1** [kyleconroy/sqlc#1439]
### Version

1.12.0

### What happened?

I tried to use named params for greater than check, but I get a syntax error. Works with `$1` in place of `@offset`. Also `sqlc.arg` does not work either.

### Relevant log output

```shell
# package query
queries/relations.sql:1:1: syntax error at or near "offset"
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS permission_group_membership (
  group_name TEXT NOT NULL,
  entity TEXT NOT NULL,
  ns TEXT NOT NULL,
  object TEXT NOT NULL,
  PRIMARY KEY(ns, group_name, entity)
);
```

### SQL queries

```sql
SELECT *
FROM permission_group_membership
WHERE entity > @offset
LIMIT 50;
```

### Configuration

```yaml
version: 1
packages:
  - path: "query"
    name: "query"
    engine: "postgresql"
    schema: "sqlcSchema.sql"
    queries: "./queries/"
    sql_package: "pgx/v4"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
