### ISSUE TITLE
Correct aggregate function variant not selected from catalog

### ISSUE THREAD

**Issue by PadraigK** [kyleconroy/sqlc#1450]
### Version

1.12.0

### What happened?

I have a query which runs an aggregate function on a column (`sum(pages)`). There are multiple variants of functions with this name (`sum`) defined in the various catalogs, e.g. `sum(numeric) → numeric, sum(integer) → integer`. 

My expectation is that the function chosen by the engine would be the one matching the type of the `pages` column parameter. Instead, the return type of the first function in the catalog that matches the name and argument count is used.  

The `ResolveFuncCall` in `public.go` doesn't seem to attempt any type matching. In the play.sqlc.dev example below, the `sum` function used is the one returning `bigint`, which is used because it is the first `sum` function defined. However there is also a variant defined which takes and returns a `numeric` type; this is the one that should be used. 

### Database schema

```sql
CREATE TABLE books (
                       id   integer PRIMARY KEY,
                       title text      NOT NULL,
                       author text     NOT NULL,
                       pages numeric      NOT NULL
);
```

### SQL queries

```sql
-- name: AuthorPages :many
select author, count(title) as num_books, SUM(pages) as total_pages
from books
group by author;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "go",
      "engine": "postgresql",
      "name": "querytest",
      "schema": "schema.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/ca51e1357b60b0ab6ed38fbb98f8e26ef30783a65cce012c90035a7abf93088c

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL, MySQL

### What type of code are you generating?

Go
