### ISSUE TITLE
Go overrides do not respect column nullability

### ISSUE THREAD

**Issue by colinking** [kyleconroy/sqlc#1457]
### Version

1.12.0

### What happened?

When you override a column type, the type is not converted to a pointer if the column is nullable.

In the example below, ideally `TeamID` becomes `*TeamStruct` when nullable similar to how `UserID` switches from `string` to `sql.NullString`:

```go
type GetUserFromTeamRow struct {
	ID     string
	UserID string
	TeamID TeamStruct
}

type GetUserRow struct {
	ID     string
	UserID sql.NullString
	TeamID TeamStruct
}
```

### Database schema

```sql
CREATE TABLE users (
    id VARCHAR(100) PRIMARY KEY
);

CREATE TABLE users_teams (
    user_id VARCHAR(100) NOT NULL,
    team_id VARCHAR(100) NOT NULL
);
```

### SQL queries

```sql
-- name: GetUserFromTeam :one
SELECT *
FROM users
JOIN users_teams ON users_teams.user_id = users.id
WHERE id = $1 and team_id = $2 LIMIT 1;

-- name: GetUser :one
SELECT *
FROM users
LEFT JOIN users_teams ON users_teams.user_id = users.id
WHERE id = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql",
      "overrides": [
        {
          "column": "users_teams.team_id",
          "go_type": {
            "type": "TeamStruct"
          }
        }
      ]
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/2f62f84b567c1ac4fd5d68b2d2fb9d302f7f4aa594aec4dcf007734d0275d39c

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
