### ISSUE TITLE
MySQL syntax error near "RETURNING *;" "

### ISSUE THREAD

**Issue by Awadabang** [kyleconroy/sqlc#1465]
### Version

1.12.0

### What happened?

A bug happened!
When I run `sqlc generate` 
I get syntax error near "RETURNING *;" "

### Relevant log output

```shell
syntax error near "RETURNING *;" "
```

### SQL queries

```sql
--name: CreateUser :one
INSERT INTO users (username, password) VALUES ($1,$2) RETURNING *;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query"
    schema: "./db/migration"
    engine: "mysql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
```

### What operating system are you using?

Windows

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
