### ISSUE TITLE
Column 'key' not found when using postgres json_each PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) 

### ISSUE THREAD

**Issue by vmantese** [kyleconroy/sqlc#1480]
### Version

1.12.0

### What happened?

When running sqlc v1.12.0

➜  rdb-api git:(feature/sqlc) ✗ sqlc compile
# package db
sql/query/advanced.sql:3:84: column "key" does not exist

It appears sqlc compile is not aware of the emitted columns by the json_each function (key and value)

### Database schema

```sql
No schema required in this mini example.
```

### SQL queries

```sql
--GetInput :one
WITH input as(
    select kv.key category,json_array_elements_text(kv.value) keyword from (select key,value from  json_each(?)) kv
)
select * from input;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    sql_package: "pgx/v4"
    path: "internal/db"
    queries: "./sql/query/"
    schema: "./sql/init/"
    engine: "postgresql"
    emit_prepared_queries: true
    emit_interface: false
    emit_exact_table_names: false
    emit_empty_slices: false
    emit_exported_queries: false
    emit_json_tags: true
    emit_result_struct_pointers: false
    emit_params_struct_pointers: false
    emit_methods_with_db_argument: false
    json_tags_case_style: "camel"
    output_db_file_name: "db.go"
    output_models_file_name: "models.go"
    output_querier_file_name: "querier.go"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
