### ISSUE TITLE
Field name not respected when using `NULLIF` in insert query

### ISSUE THREAD

**Issue by go-mez** [kyleconroy/sqlc#1506]
### Version

1.12.0

### What happened?

When generating an insert query using the `NULLIF` function, the field name is not respected and will be generated as `nullif`.

### Relevant log output

```shell
type CreateAlarmParams struct {
	NULLIF    interface{}
	CreatedBy sql.NullInt32
}
```

### Database schema

```sql
CREATE TABLE alarms (
	alarm_title varchar(30),
  	created_by int(11)
);
```

### SQL queries

```sql
-- name: CreateAlarm :execresult
INSERT INTO alarms (
  alarm_title, 
  created_by
) VALUES 
(
  NULLIF(?, ''), 
  ?
);
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/fbe1bfb0158f637dd53b3ad90e19ecdc59c27fbf7568cd332b9a120af81f39cc

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
