### ISSUE TITLE
Using :batchexec produces "invalid query type: :batchexec"

### ISSUE THREAD

**Issue by austincollinpena** [kyleconroy/sqlc#1508]
### Version

1.12.0

### What happened?

When trying to use a `:batchexec` parameter, I got an error saying:

```
invalid query type: :batchexec
```

### Relevant log output

```shell
invalid query type: :batchexec
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: BulkUpdate :batchexec
UPDATE authors
SET name = $1
WHERE id = $2;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql",
	  "sql_package": "pgx/v4"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/0cda343d6fed7f710fd69f13ce982d7bcb423eee69bce1b6447c445756387359

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
