### ISSUE TITLE
Doc comments are not attached to generated func (Go)

### ISSUE THREAD

**Issue by eandre** [kyleconroy/sqlc#1575]
### Version

1.12.0

### What happened?

I tried to get sqlc to propagate comments next to the SQL query to the generated function to serve as documentation.

Output (go):
```go
`

// GetCronJobByID gets a cron job by its id.

func (q *Queries) GetCronJobByID(ctx context.Context, db DBTX, id uuid.UUID) (*CronCronJob, error) {
    // ...
}
```

Since there is a newline between the `// GetCronJobByID gets a cron job by its id.` comment and the function the comment does not show up as a documentation comment. It would be great if the extra newline is removed.

Interestingly I can't reproduce this in the sqlc playground. Not sure why.

### SQL queries

```sql
const getCronJobByID = `-- name: GetCronJobByID :one
SELECT id, app_id, env_id, job_id, name, description, schedule, rpc_path, http_method, created_deploy_id, deleted_deploy_id, created, deleted FROM cron.cron_job WHERE id = $1
```

### Configuration

```yaml
version: 1
packages:
  - path: "pkg/db"
    queries: "pkg/db/queries"
    engine: "postgresql"
    sql_package: "pgx/v4"
    emit_empty_slices: true
    emit_methods_with_db_argument: true
    emit_result_struct_pointers: true
    emit_interface: true
    schema: "pkg/db/migrations"
    output_db_file_name: "sqlc_db.go"
    output_models_file_name: "sqlc_models.go"
    output_querier_file_name: "sqlc_querier.go"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
