### ISSUE TITLE
citext on column resulted to interface{} as type

### ISSUE THREAD

**Issue by vijaynallagatla** [kyleconroy/sqlc#1581]
### Version

Other

### What happened?

Version
Other

What happened?
Hint: I am using v1.13.0 with `PostgreSQL` DB to generate the Go code. 

### Result:
```json
type AddNameParams struct {
	Name interface{}
}
```

### Expectation:
```json
type AddNameParams struct {
	Name string
}
```

Type `citext` should be supported as a `String` 

### Database schema

```sql
CREATE TABLE IF NOT EXISTS temp(id uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(), name citext NOT NULL)
```

### SQL queries

```sql
INSERT INTO (name) VALUES('name')
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by FlymeDllVa** [comment]
Why doesn't this option work as a crutch?

```yaml
        overrides:
          - db_type: "pg_catalog.citext"
            go_type: "string"
```
