### ISSUE TITLE
sqlc.yaml works but sqlc.yml doesnt

### ISSUE THREAD

**Issue by ggratte** [kyleconroy/sqlc#1591]
### Version

Other

### What happened?

A bug happened!

### Relevant log output

```shell
""
```

### Database schema

```sql
""
```

### SQL queries

```sql
""
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
