### ISSUE TITLE
Arguments not recognized in json path expressions

### ISSUE THREAD

**Issue by stephen** [kyleconroy/sqlc#1603]
### Version

1.13.0

### What happened?

When using [jsonpath (`@?`)](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-SQLJSON-PATH) operations in postgres, sqlc doesn't recognize any of the forms for query input arguments.

input:
```
CREATE TABLE entries (
  id integer not null,
  entry jsonb not null,
  primary key (id)
);

-- name: GetEntry :one
select * from entries
  where entry @? '$.a[*] ? (@.b == "@expr")'
  or entry @? '$.a[*] ? (@.b == "sqlc.arg(expr)")'
  or entry @? '$.a[*] ? (@.b == "$1")'
  limit 1;
```

output:
```
```

### Relevant log output

```shell
n/a
```

### Database schema

```sql
CREATE TABLE entries (
  id integer not null,
  entry jsonb not null,
  primary key (id)
);
```

### SQL queries

```sql
-- name: GetEntry :one
select * from entries
  where entry @? '$.a[*] ? (@.b == "@expr")'
  or entry @? '$.a[*] ? (@.b == "sqlc.arg(expr)")'
  or entry @? '$.a[*] ? (@.b == "$1")'
  limit 1;
```

### Configuration

```yaml
{
  "version": 1,
  "packages": [
    {
      "name": "models",
      "path": "internal/models/",
      "engine": "postgresql",
      "schema": "internal/models/migrations/",
      "queries": "internal/models/",
      "sql_package": "pgx/v4",
      "emit_exported_queries": true
    }
  ],
  "overrides": [
    {
      "column": "entries.Entry",
      "go_type": "github.com/stephen/etc/entry.Entry"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/5578358bb9d81fe7b82e1c6d21e4cb7e4609caeaa35beba19ef2559b708726d2

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
