### ISSUE TITLE
Parameters not recognized in jsonpath expressions

### ISSUE THREAD

**Issue by stephen** [kyleconroy/sqlc#1604]
### Version

1.13.0

### What happened?

When using [jsonpath (`@?`)](https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-SQLJSON-PATH) operations in postgres, sqlc doesn't recognize any of the forms for query input arguments.

input:
```sql
CREATE TABLE entries (
  id integer not null,
  entry jsonb not null,
  primary key (id)
);

-- name: GetEntry :one
select * from entries
  where entry @? '$.a[*] ? (@.b == "@expr")'
  or entry @? '$.a[*] ? (@.b == "sqlc.arg(expr)")'
  or entry @? '$.a[*] ? (@.b == "$1")'
  limit 1;
```

output:
```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: query.sql

package db

import (
	"context"
)

const getEntry = `-- name: GetEntry :one
select id, entry from entries
  where entry @? '$.a[*] ? (@.b == "@expr")'
  or entry @? '$.a[*] ? (@.b == "sqlc.arg(expr)")'
  or entry @? '$.a[*] ? (@.b == "$1")'
  limit 1
`

func (q *Queries) GetEntry(ctx context.Context) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry)
	var i Entry
	err := row.Scan(&i.ID, &i.Entry)
	return i, err
}
```

I'd expect `GetEntry` to take an argument (presumably of type `json.RawMessage`).

### Relevant log output

```shell
n/a
```

### Database schema

```sql
CREATE TABLE entries (
  id integer not null,
  entry jsonb not null,
  primary key (id)
);
```

### SQL queries

```sql
-- name: GetEntry :one
select * from entries
  where entry @? '$.a[*] ? (@.b == "@expr")'
  or entry @? '$.a[*] ? (@.b == "sqlc.arg(expr)")'
  or entry @? '$.a[*] ? (@.b == "$1")'
  limit 1;
```

### Configuration

```yaml
{
  "version": 1,
  "packages": [
    {
      "name": "models",
      "path": "internal/models/",
      "engine": "postgresql",
      "schema": "internal/models/migrations/",
      "queries": "internal/models/",
      "sql_package": "pgx/v4",
      "emit_exported_queries": true
    }
  ],
  "overrides": [
    {
      "column": "entries.Entry",
      "go_type": "github.com/stephen/etc/entry.Entry"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/5578358bb9d81fe7b82e1c6d21e4cb7e4609caeaa35beba19ef2559b708726d2

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
