### ISSUE TITLE
Override is not working for int32 type out of struct fields.

### ISSUE THREAD

**Issue by Dancheg97** [kyleconroy/sqlc#1611]
### Version

1.13.0

### What happened?

I recieved int32 type in generated code after using override in config:

Actual code:
```go
const exampleQuery = `-- name: Example :one
INSERT INTO org_elements (one, two, three, four)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type OrgElemCreateChildParams struct {
	One *uint64
	Two *uint64
	Three *uint64
	Four *uint64
}

func (q *Queries) OrgElemCreateChild(ctx context.Context, arg ExampleParams) (int32, error) {
	row := q.db.QueryRow(ctx, exampleQuery,
		arg.One,
		arg.Two,
		arg.Three,
		arg.Four,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
```

Expected code:
```go
const exampleQuery = `-- name: Example :one
INSERT INTO org_elements (one, two, three, four)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type OrgElemCreateChildParams struct {
	One *uint64
	Two *uint64
	Three *uint64
	Four *uint64
}

func (q *Queries) OrgElemCreateChild(ctx context.Context, arg ExampleParams) (uint64, error) {
	row := q.db.QueryRow(ctx, exampleQuery,
		arg.One,
		arg.Two,
		arg.Three,
		arg.Four,
	)
	var id uint64
	err := row.Scan(&id)
	return id, err
}
```

### Relevant log output

```shell
-
```

### Database schema

```sql
CREATE TABLE example (
    one SERIAL PRIMARY KEY,
    two INTEGER,
    three INTEGER,
    four INTEGER
);
```

### SQL queries

```sql
-- name: Example :one
INSERT INTO example (one, two, three, four)
VALUES ($1, $2, $3, $4)
RETURNING id;
```

### Configuration

```yaml
version: 1
packages:
  - path: "postgres/sqlc"
    name: "sqlc"
    engine: "postgresql"
    schema: "migrations/"
    queries: "sqlc.sql"
    emit_interface: true
    emit_prepared_queries: true
    sql_package: "pgx/v4"
overrides:
  - go_type: 
      type: "uint64"
      pointer: true
    db_type: "pg_catalog.int4"
    nullable: true
  - go_type: 
      type: "uint64"
    db_type: "pg_catalog.int4"
```

### Playground URL

https://play.sqlc.dev/p/0533fcf8e31d59621157614ec301f42e8e7debf4b4c850a2889928c966d49498

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
sqlc treats SERIAL types differently, so you'll need to change your overrides to this:

```
version: 1
packages:
  - path: "postgres/sqlc"
    name: "sqlc"
    engine: "postgresql"
    schema: "migrations/"
    queries: "sqlc.sql"
    emit_interface: true
    emit_prepared_queries: true
    sql_package: "pgx/v4"
overrides:
  - go_type: 
      type: "uint64"
      pointer: true
    db_type: "pg_catalog.int4"
    nullable: true
  - go_type: 
      type: "uint64"
    db_type: "serial"
```
