### ISSUE TITLE
Ignore Column

### ISSUE THREAD

**Issue by daaku** [kyleconroy/sqlc#162]
It would be nice if the override config would also allow for a column to be ignored. Since the `*` is converted to a real list of columns in the generated code, this seems like it should be possible to do. FWIW, my use case is a `tsvector` column.

**Comment by kyleconroy** [comment]
Instead of adding a special case for ignored columns, I'd rather roll this feature in query templates (#112). I also don't want to change the behavior of `*`, which is part of the SQL standard.

**Comment by daaku** [comment]
:+1:

**Comment by carlmjohnson** [comment]
Same problem. I guess my workaround is to create a materialized view instead?

**Comment by carlmjohnson** [comment]
Hacky idea from #1380: maybe I can just have an extra schema file that says `alter table page drop column fts` and just never run it in production…

**Comment by mortenson** [comment]
In case it helps future people, I ended up using column overrides for this to coerce the type into `string`:

```
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries"
    schema: "db/schema"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "src/db"
        overrides:
          - column: "messages.full_text_search"
            go_type: "string"
```

It's a generated column so shouldn't really matter for it to be scanned, just wanted the error ignored.
