### ISSUE TITLE
invalid query type: :execlastid

### ISSUE THREAD

**Issue by 0RAJA** [kyleconroy/sqlc#1636]
### Version

1.13.0

### What happened?

我在使用sqlc对mysql的sql代码进行转换，我希望能够在插入数据后返回主键ID，但是在我执行`sqlc generate`却提醒我`invalid query type: :execlastid`,但我不清楚为什么会这样。

### Relevant log output

```shell
sqlc generate
# package db
internal/dao/mysql/query/user.sql:1:1: invalid query type: :execlastid
make: *** [Makefile:16：sqlc] 错误 1
```

### Database schema

```sql
create table if not exists user
(
    id             int primary key auto_increment,
    name           varchar(40) not null unique,
    password       varchar(128) not null,
    follow_count   int         not null default 0,
    follower_count int         not null default 0,
    constraint user_name unique index (name)
) default charset = utf8;
```

### SQL queries

```sql
-- name: CreateUser :execlastid
INSERT INTO user (name, password)
VALUES (?, ?);
```

### Configuration

```yaml
version: 1
packages:
  - name: "db" # package name
    path: "internal/dao/mysql/sqlc" # 生成代码路径
    engine: "mysql" # 引擎
    schema: "internal/dao/mysql/migration" # 表结构
    queries: "internal/dao/mysql/query/" # 查询语句
    emit_json_tags: true # 将json放到标签
    emit_empty_slices: true # 查不到值返回空切片
    emit_interface: true # 生成包含查询结构所有功能的接口
```

### Playground URL

https://play.sqlc.dev/p/111afa6ea6fca75bb5c94e03723bdc6eb233b0487704853253cab61a06adb2c2

### What operating system are you using?

Linux

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
