### ISSUE TITLE
IN() in MySQL not working

### ISSUE THREAD

**Issue by mrunzo** [kyleconroy/sqlc#1642]
### Version

1.13.0

### What happened?

I tried to select the records by using IN() in MySQL but it does not work and gave me an error. Isn't this support, a bug, or something?

### Relevant log output

```shell
sqlc generate failed.
# package db
query.sql:9:16: syntax error near "::int[]);" "
```

### Database schema

```sql
CREATE TABLE authors (
  id         SERIAL PRIMARY KEY,
  bio        text   NOT NULL,
  birth_year int    NOT NULL
);
```

### SQL queries

```sql
SELECT * FROM authors
WHERE id IN($1::int[]);
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/bdec285b67c176fd9b8a9fc10605266dd2ba19111c5455541c3c0c81b60cc104

### What operating system are you using?

Windows

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
