### ISSUE TITLE
Query Parameter type is not removed from SQL statement sent to DB

### ISSUE THREAD

**Issue by JonasHiltl** [kyleconroy/sqlc#1650]
### Version

1.13.0

### What happened?

I'm using Postgis and want to insert a Point through sqlc.
I have setup sqlc to convert all `geometry` db types to [go-postgis.Point](https://github.com/cridenour/go-postgis/blob/master/point.go#L10) types.
Here is the specific config:
```yaml
overrides:
  - db_type: "geometry"
    go_type: "github.com/cridenour/go-postgis.Point"
```
Since I'm using the Postgis `ST_GeomFromEWKB` function to convert my `go-postgis.Point` to an actual Geometry Point in Postgis, sqlc can't automatically infer the type of the parameter, since it is wrapped with the `ST_GeomFromEWKB` function. So I added  `::geometry` to the parameter which maps the correct `go-postgis.Point` type to the parameter.
But when I have a look at the generated SQL query the `::geometry` type specified on the parameter is not ommited and gets send to the DB which results in a parse error from Postgis.

### Relevant log output

```shell
INSERT INTO parties (
  id, 
  user_id,
  title,
  is_public,
  location,
  street_address,
  postal_code,
  state,
  country,
  start_date,
  end_date
) VALUES (
  $1, $2, $3, $4, ST_GeomFromEWKB($5::geometry), $6, $7, $8, $9, $10, $11
)
RETURNING id, user_id, title, is_public, location, street_address, postal_code, state, country, start_date, end_date

2022-05-28 21:06:46.914 UTC [442] ERROR:  parse error - invalid geometry
2022-05-28 21:06:46.914 UTC [442] HINT:  "\x" <-- parse error at position 2 within geometry
2022-05-28 21:06:46.914 UTC [442] STATEMENT:  -- name: CreateParty :one
```

### Database schema

```sql
CREATE TABLE parties (
    id char(27) PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    is_public BOOLEAN NOT NULL DEFAULT false,
    location geometry(POINT) NOT NULL,
    street_address TEXT,
    postal_code TEXT,
    state TEXT,
    country TEXT,
    start_date TIMESTAMP,
    end_date TIMESTAMP
);
```

### SQL queries

```sql
INSERT INTO parties (
  id, 
  user_id,
  title,
  is_public,
  location,
  street_address,
  postal_code,
  state,
  country,
  start_date,
  end_date
) VALUES (
  $1, $2, $3, $4, ST_GeomFromEWKB($5::geometry), $6, $7, $8, $9, $10, $11
)
RETURNING *;
```

### Configuration

```yaml
version: 1
packages:
  - name: "repository"
    path: "./repository"
    queries: "./repository/queries"
    schema: "./repository/migrations"
    engine: "postgresql"
    sql_package: "pgx/v4"
    emit_json_tags: false
    emit_prepared_queries: false
    emit_interface: true
    emit_exact_table_names: false
overrides:
  - db_type: "geometry"
    go_type: "github.com/cridenour/go-postgis.Point"
```

### Playground URL

https://play.sqlc.dev/p/7896c9d81dfbb932f1c08ed737715de967aa1fe1226613c1d82e03bac5a886f9

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
