### ISSUE TITLE
function "sqlc.narg" does not exist

### ISSUE THREAD

**Issue by akhilmhdh** [kyleconroy/sqlc#1667]
### Version

1.13.0

### What happened?

As per the documentation i tried to use `sqlc.narg` in my query. But getting an error

```
: function "sqlc.narg" does not exist
```

I think there is also a typo in [documentation](https://docs.sqlc.dev/en/latest/howto/named_parameters.html#nullable-parameters). On top para says to use `sql.narg` but code example show `sqlc.narg` 

 I tried this but failed completely as the argument itself was ignored. I am able to use sqlc.arg but not narg.

I can raise a PR for fixing the  documentation if its a typo which i think it is, as i went through your test data in codebase and saw `sqlc.narg`

Tried both v2 and v1 config. Is this yet to release 😅 , sorry if I pulled the trigger early

### Relevant log output

```shell
: function "sqlc.narg" does not exist
```

### Database schema

```sql
CREATE TABLE teams (
	id uuid DEFAULT public.uuid_generate_v4() PRIMARY KEY,
	name varchar(50) NOT NULL,
);
```

### SQL queries

```sql
UPDATE 
  teams
SET
  name = COALESCE(sqlc.narg('name'), teams.name)
WHERE 
  teams.id = @team_id
RETURNING teams.*;
```

### Configuration

```yaml
version: 2
sql:
  - engine: "postgresql"
    schema: "db/schemas"
    queries: "internal/db/queries"
    gen:
      go:
        package: "db"
        out: "internal/db"
        emit_interface: true
        emit_params_struct_pointers: true
        emit_json_tags: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
