### ISSUE TITLE
AVG should be nullable

### ISSUE THREAD

**Issue by odannyc** [kyleconroy/sqlc#1691]
### Version

1.14.0

### What happened?

I have the following query: 

```sql
SELECT AVG(rating)
FROM product_ratings
WHERE product_id = 1234;
```

This generates the following go code:

```go
var avg string
err := row.Scan(&avg)
```

Notice how it uses a `string` for avg. I would like it to use an `int`, so I cast it like so:

```sql
SELECT AVG(rating)::int
FROM product_ratings
WHERE product_id = 1234;
```

Which generates the following code:

```go
var column_1 int32
err := row.Scan(&column_1)
```

Now, my issue is that the `product_ratings` table might not always have entries for all products so if the `AVG(rating)` statement returns `NULL` for a specific product, I get the following error:

```
sql: Scan error on column index 0, name "avg": converting NULL to int32 is unsupported
```

Is there a way to force sqlc to generate sql.NullInt32 instead of just int32?

### Relevant log output

```shell
sql: Scan error on column index 0, name "avg": converting NULL to int32 is unsupported
```

### Database schema

```sql
CREATE TABLE product_ratings
(
  rating      smallint NOT NULL CHECK ( score <= 5 AND score >= 1 ),
  product_id  int      NOT NULL REFERENCES products (id)
);

CREATE TABLE products
(
   id    serial PRIMARY KEY,
   name  VARCHAR(255)  NOT NULL
);
```

### SQL queries

```sql
SELECT AVG(rating)::int
FROM product_ratings
WHERE product_id = 1234;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "sql"
    path: "./internal/store/sql"
    queries: "./internal/store/sql/queries/"
    schema: "./internal/store/sql/migrations/"
    engine: "postgresql"
    emit_db_tags: true
    emit_prepared_queries: true
    emit_interface: false
    emit_exact_table_names: false
    emit_empty_slices: true
    emit_json_tags: true
    json_tags_case_style: "camel"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
