### ISSUE TITLE
type overriding not working correctly

### ISSUE THREAD

**Issue by otabe555** [kyleconroy/sqlc#1697]
### Version

1.14.0

### What happened?

A bug happened!

after overridng postgres uuid type to external uuid package its not replacing default "github.com/google/uuid" to "github.com/gofrs/uuid
![Screenshot from 2022-06-22 11-37-34](https://user-images.githubusercontent.com/31259774/174960194-10570bf9-443f-4a28-a045-70dbd6789df2.png)
In other folder its not even replacing (i used only insert there).
![Screenshot from 2022-06-22 11-38-21](https://user-images.githubusercontent.com/31259774/174960326-f494efb2-1718-41e5-9818-65bb2fe273f4.png)
"

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "name": "db",
      "path": "./storage/postgres",
      "engine": "postgresql",
      "schema": "./migrations/",
      "queries": "./storage/queries/",
      # "emit_prepared_queries": false,
      # "emit_interface": false,
      # "emit_exact_table_names": false,
      # "emit_empty_slices": false,
      # "emit_exported_queries": false,
      "emit_json_tags": true,
      "sql_package": "pgx/v4",
      "output_db_file_name": "postgres.go",
      "json_tags_case_style": "camel"
    }
  ],
  "overrides": [
    {
      "go_type": "github.com/gofrs/uuid.UUID",
      "db_type": "uuid"
    }
  ]
}
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
