### ISSUE TITLE
override double importing external packages

### ISSUE THREAD

**Issue by otabe555** [kyleconroy/sqlc#1698]
### Version

1.14.0

### What happened?

A bug happened!

i wanted to replace default uuid type "github.com/google/uuid" to "github.com/gofrs/uuid", after generating query it keeps importing both libraries.

### Database schema

```sql
CREATE TABLE IF NOT EXISTS "transaction" (
    "id" bigserial PRIMARY KEY,
    "order_id" UUID REFERENCES "order"("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "order"(
    id UUID PRIMARY KEY,
    current_modification_id UUID
);
```

### SQL queries

```sql
-- name: PlaceOrder :one
INSERT INTO "order"(
        id,
		current_modification_id
	) VALUES (
		$1::uuid,
		$2::uuid
	)
    RETURNING "id", "current_modification_id";

-- name: GetOrderByID :one
SELECT * FROM "order" WHERE id = $1;

-- name: GetOrdersList :many
SELECT
	count("id") over(),
    *
FROM "order"
WHERE true
LIMIT sqlc.arg('limit')::INT OFFSET (sqlc.arg('page')::INT-1)*sqlc.arg('limit')::INT;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ],
  "overrides": [{
   "go_type": "github.com/gofrs/uuid.UUID",
      "db_type": "uuid"
	  }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/ce67c05d25b52e59ffdeeabe852bf1e3c92e1673999e3073a527de5e43f080fc

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
