### ISSUE TITLE
No quotes around column names in Postgres

### ISSUE THREAD

**Issue by gurleensethi** [kyleconroy/sqlc#1718]
### Version

1.14.0

### What happened?

SQLC is not adding quotes around columns in postgresql.

Query:
```sql
SELECT * FROM "Article";
```

Generated Query
```sql
SELECT id, title, publishDate FROM "Article";
```

No `""` quotes around `publishDate` since it is camelCase 🤷‍♂️.

How can I get sqlc to generate query like this:

```sql
SELECT "id", "title", "publishDate" FROM "Article";
```

### SQL queries

```sql
SELECT * FROM "Article";
```

### Configuration

```yaml
version: 2
sql:
- engine: "postgresql"
  schema: "./pkg/db/migrations"
  queries: "./pkg/db/queries.sql"
  gen:
    go:
      package: "dbgen"
      out: "./pkg/db/dbgen"
      json_tags_case_style: camelCase
      emit_db_tags: true
```

_No response_

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
