### ISSUE TITLE
Primary key of more than one column not set as NOT NULL

### ISSUE THREAD

**Issue by GetPsyched** [kyleconroy/sqlc#1721]
### Version

1.14.0

### What happened?

I have a table which has 2 columns set as the primary key. This means that both the columns must be NOT NULL. But this does not reflect on the model struct generated by SQLC and is instead shown of the type `sql.NullInt32`.

### Database schema

```sql
CREATE TABLE IF NOT EXISTS group_faculty (
    group_name  VARCHAR(50) REFERENCES groups(name),
    emp_id      INT         REFERENCES faculty(emp_id),
    PRIMARY KEY (group_name, name)
);
```

### SQL queries

```sql
-- name: CreateGroupFaculty :exec
INSERT INTO group_faculty (
    group_name, emp_id
)
VALUES (
    (SELECT g.name from groups g WHERE g.name = $1 or g.alias = $1),
    $2
);
```

### Configuration

```yaml
version: 1
packages:
  - name: "query"
    path: "internal/query"
    queries: "./sql/queries"
    schema:
      - "./sql/schemas/student.sql"
      - "./sql/schemas/faculty.sql"
      - "./sql/schemas/group.sql"
      - "./sql/schemas/guild.sql"
      - "./sql/schemas/course.sql"
    engine: "postgresql"
    emit_json_tags: true
    json_tags_case_style: "snake"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
