### ISSUE TITLE
Allow overrides for code generation via plugins

### ISSUE THREAD

**Issue by alexbiehl** [kyleconroy/sqlc#1723]
### What do you want to change?

I have a sqlc.yaml that looks like this 

```
version: 2
plugins:
  - name: haskell
    process: 
      cmd: haskell-sqlc-plugin
sql:
  - engine: "postgresql"
    schema: 
      - db/migrations
    queries: 
      - db/queries
    codegen:
      - out: gen
        plugin: haskell
```

It would be great if I could specify my plugin related overrides in the the codegen section for the `haskell` plugin. e.g. 

```
    codegen:
      - out: gen
        plugin: haskell
        overrides:
          - column: "scarfdb.packages.id"
            code_type: "Scarf.Modles.Types.PrimaryKey Scarf.Models.Package"
```

**Comment by kyleconroy** [comment]
This is actually possible, but there's a few hoops you have to jump through.

You can pass a JSON blob to your plugin via the "options" key. It will get passed to your plugin as a string, so you'll need to parse it in your plugin. Here's an example:

https://github.com/kyleconroy/sqlc/blob/main/internal/endtoend/testdata/process_plugin_sqlc_gen_json/sqlc.json

**Comment by alexbiehl** [comment]
I see. Would you be open to a contribution that would make passing overrides to plugins a bit more explicit?

**Comment by kyleconroy** [comment]
> Would you be open to a contribution that would make passing overrides to plugins a bit more explicit?

Not at this time. The reason is that overrides weren't designed to work with arbitrary plugins. You can pass your overrides with one additional layer of nesting.

```
    codegen:
      - out: gen
        plugin: haskell
        options:
          overrides:
            - column: "scarfdb.packages.id"
              code_type: "Scarf.Modles.Types.PrimaryKey Scarf.Models.Package"
```

>  communicating json over to the plugin kinda defeats the purpose of the clean interface again.

This is true, but it's a difficult problem to solve since sqlc doesn't know what types / options plugins support at runtime.
