### ISSUE TITLE
the PostgreSQL engine does not support Windows

### ISSUE THREAD

**Issue by karangadani** [kyleconroy/sqlc#1777]
### Version

1.14.0

### What happened?

I have started learning Go recently and came across this error while running "sqlc generate" command. 

How do I resolve this error ?? 

### Relevant log output

```shell
# package db
D:\Projects\golang-learnings\simplebankProject\db\migration\000001_init_schema.up.sql:1:1: the PostgreSQL engine does not support Windows
```

### SQL queries

```sql
-- name: CreateAccount :one
INSERT INTO accouts (
  owner,balance,currency
) VALUES (
  $1, $2, $3
)
RETURNING *;
```

### Configuration

```yaml
version: "1"
packages:
  - name: "db"
    path: "./db/sqlc"
    queries: "./db/query/"
    schema: "./db/migration/"
    engine: "postgresql"
    emit_json_tags: true
    emit_prepared_queries: false
    emit_interface: false
    emit_exact_table_names: false
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
