### ISSUE TITLE
Batch queries referencing only schema types missing imports for `pgtype` and `database/sql`

### ISSUE THREAD

**Issue by chrisyxlee** [kyleconroy/sqlc#1792]
### Version

Other

### What happened?

Version: 1.15.0

Similar to #1682 

`batch.go` fails to import `"github.com/jackc/pgtype"` and `"database/sql"` for batch queries statements when only the schema references the type.

The imports are correct when one of the parameters for the query use that specific type (e.g. `WHERE bio = $1::JSONB` will import the correct packages).

### Relevant log output

```shell
n/a
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  bio  JSONB,
  published BOOLEAN
);
```

### SQL queries

```sql
-- name: GetAuthor :batchone
SELECT bio, published FROM authors
WHERE id = $1
LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql",
      "sql_package": "pgx/v4"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/bc8d330bd6e53ca6ad3cd34b15d184c4a6a99e2a19b205cbd08cb754b543ca16

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
