### ISSUE TITLE
"Getting started with PostgreSQL" instructions do not succeed

### ISSUE THREAD

**Issue by abedef** [kyleconroy/sqlc#1801]
### Version

Other

### What happened?

After following the instructions at [Getting started with PostgreSQL](https://docs.sqlc.dev/en/latest/tutorials/getting-started-postgresql.html), the step copied below fails:

>You are now ready to generate code. Run the generate command. You shouldn’t see any errors or output.
>
>```
>sqlc generate
>```

The following output is printed when the above command is run:

>```
># package tutorial
>query.sql:1:1: syntax error at or near "WHERE"
>```

### Database schema

```sql
CREATE TABLE authors (
	id   BIGSERIAL PRIMARY KEY,
	name text      NOT NULL,
	bio  text
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;

-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;

-- name: CreateAuthor :one
INSERT INTO authors (
	name, bio
) VALUES (
	$1, $2
)
RETURNING *;

-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1;

-- name: UpdateAuthor :one
UPDATE authors
set name = $2,
bio = $3,
WHERE id = $1
RETURNING *;
```

### Configuration

```yaml
version: 1
packages:
  - path: "tutorial"
    name: "tutorial"
    engine: "postgresql"
    schema: "schema.sql"
    queries: "query.sql"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
