### ISSUE TITLE
sqlc.narg ignored with array cast

### ISSUE THREAD

**Issue by SN9NV** [kyleconroy/sqlc#1851]
### Version

1.15.0

### What happened?

In the playground example I supplied, you can see that I have used both `argc.arg` and `sqlc.narg` when casting to `TEXT[]`, but the generated code does not contain `sql.NullString` for the second argument as I expected.

Input:
```sql
-- name: batchUpsert :exec
INSERT INTO authors (id, name, bio)
VALUES (
  unnest(sqlc.arg(ids)::BIGINT[]),
  unnest(sqlc.arg(names)::TEXT[]),
  unnest(sqlc.narg(bios)::TEXT[])
) ON CONFLICT (id) DO UPDATE SET
	name = EXCLUDED.name,
	bio = EXCLUDED.bio;
```

Output:
```go
type batchUpsertParams struct {
	Ids   []int64
	Names []string
	Bios  []string
}
```

Expected:
```go
type batchUpsertParams struct {
	Ids   []int64
	Names []string
	Bios  []sql.NullString
}
```

If I take away the array part of the cast, so `::TEXT` instead of `::TEXT[]`, it seems to work as expected, so I assume that this is a bug, and not intentional.

If there are any other way to have a dynamic batching system someone could recommend, I will give that a try, but so far, this is what I have.

Thanks

### Playground URL

https://play.sqlc.dev/p/b0fb935d443804af71bba41ac58800b54db5992209579ec08d27e00b6a61a111

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by SN9NV** [comment]
I solved my problem by overriding the generated types to use the `pgtype` package because these types are nullable. Then I create dependency inversion functions which take in the application types and converts them to the `pgtype` types.

So my `sqlc.yaml` looks something like this:
```yaml
version: 2
sql:
  - engine: "postgresql"
    gen:
      go:
        sql_package: "pgx/v4"
        overrides:
          - db_type: "uuid"
            go_type: "github.com/jackc/pgtype.UUID"
          - db_type: "text"
            go_type: "github.com/jackc/pgtype.Text"
```

**Comment by dhermes** [comment]
Here is a slightly more focused hack. Introduce an alias type in the DB, e.g.

```sql
CREATE DOMAIN UUID_NULL_ALIAS AS UUID;
COMMENT ON DOMAIN UUID_NULL_ALIAS IS 'Alias for UUID; introduced to workaround sqlc bug';
```

Configure via

```yaml
---
version: "2"
overrides:
  go:
    overrides:
      - go_type: github.com/google/uuid.NullUUID
        db_type: uuid_null_alias
        nullable: true
      - go_type: github.com/google/uuid.NullUUID
        db_type: uuid_null_alias
        nullable: false
# ...
```

and then use

```sql
-- name: BatchInsert :exec
INSERT INTO
  authors (id, name, bio)
VALUES (
  unnest(sqlc.arg(ids)::UUID_NULL_ALIAS[]),
  unnest(sqlc.arg(names)::TEXT[]),
  unnest(sqlc.narg(bios)::TEXT[])
);
```
