### ISSUE TITLE
MySQL: integer types for int8 and int16 are missing and use int32

### ISSUE THREAD

**Issue by Funzinator** [kyleconroy/sqlc#1856]
### Version

1.15.0

### What happened?

For MySQL, the usage of SMALLINT and TINYINT (except TINYINT(1)) result in int32 while int16 and int8 respectively would be the correct choice.
The PostgreSQL implementation does map correctly.

### Database schema

```sql
CREATE TABLE authors (
  id   INT UNSIGNED PRIMARY KEY,
  id_author SMALLINT NOT NULL,
  id_name BIGINT NOT NULL
);
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/62380b5c7ae894a511e870a044c334871d577b9fec10a9f11fdd4c114e7ba3b1

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
