### ISSUE TITLE
PostgreSQL: Type overrides lost when selecting from a CTE

### ISSUE THREAD

**Issue by haines** [kyleconroy/sqlc#1862]
### Version

1.15.0

### What happened?

Rows returned by selecting from a CTE don't have the custom type overrides from the underlying columns. Parameters to the queries in the CTE do have the correct types.

In the example below, I expected to generate 

```go
func (q *Queries) FindOrCreateUser(ctx context.Context, email user.Email) (user.ID, error)
```

but I only got the correct type on the parameter while the result was the default type:

```go
func (q *Queries) FindOrCreateUser(ctx context.Context, email user.Email) (int64, error)
```

### Database schema

```sql
CREATE TABLE users (
  id bigserial PRIMARY KEY,
  email text NOT NULL CONSTRAINT unique_email UNIQUE
);
```

### SQL queries

```sql
WITH inserted AS (
  INSERT INTO users (email)
  VALUES ($1)
  ON CONFLICT DO NOTHING
  RETURNING id
)
SELECT id
FROM inserted
UNION ALL
SELECT id
FROM users
WHERE email = $1;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [
    {
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql",
      "gen": {
        "go": {
          "out": "db",
          "overrides": [
            {
              "column": "users.id",
              "go_type": "example.com/user.ID"
            },
			{
              "column": "users.email",
              "go_type": "example.com/user.Email"
            }
          ]
        }
      }
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/61a01b4b0274dda093580349d104add205ecece9ac580dfc2fefc4d9a06b62fa

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
