### ISSUE TITLE
pgx timestamp support is not being generated

### ISSUE THREAD

**Issue by peschkaj** [kyleconroy/sqlc#1865]
### Version

1.15.0

### What happened?

sqlc does not take advantage of pgx/v4 when generating `sql.query.go`

Although `db.go` generates the pgx/v4 import, `sql.query.go` does not use any of the types supported by pgx/v4. This results in a loss of precision for types like `timestamptz` - the generated code uses `sql.NullTime` instead and loses fractional seconds.

### Database schema

```sql
-- Example queries for sqlc
CREATE SCHEMA togo;
CREATE TABLE IF NOT EXISTS togo.tasks (
    id BIGSERIAL PRIMARY KEY ,
    name VARCHAR(100) NOT NULL,
    description VARCHAR NOT NULL,
    created_on TIMESTAMPTZ(6) NOT NULL,
    completed_on TIMESTAMPTZ(6) NULL,
    due_date TIMESTAMPTZ(6) NULL
);
```

### SQL queries

```sql
-- name: AllTasks :many
SELECT * FROM togo.tasks;

-- name: RemoveTask :exec
DELETE FROM togo.tasks WHERE name = $1;

-- name: AddOrUpdateTask :exec
INSERT INTO togo.tasks (name, description, created_on, completed_on, due_date)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (name) DO UPDATE
    SET description = $2, created_on = $3, completed_on = $4, due_date = $5;

-- name: FindByName :one
SELECT * FROM togo.tasks WHERE name = $1;

-- name: FindByDueDate :many
SELECT * FROM togo.tasks WHERE due_date = $1;

-- name: FindOverdueTasks :many
SELECT * FROM togo.tasks WHERE due_date < $1;

-- name: CountTasks :one
SELECT COUNT(*) FROM togo.tasks;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "query.sql"
    gen:
      go:
        package: "postgres"
        sql_package: "pgx/v4"
        out: "."
```

### Playground URL

https://play.sqlc.dev/p/3860b78b43c8e9f605454a012c3c691d8ec20e8999b49ab2e5419fc77d6f42a8

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
