### ISSUE TITLE
go_struct_tag is missing for generated result row struct (or how to configure it)

### ISSUE THREAD

**Issue by avucic** [kyleconroy/sqlc#1867]
### Version

1.15.0

### What happened?

When I use given configuration I can see generated tag in `models` file.

```go
type Account struct {
	ID          uuid.UUID `sometagtype:"some_value"`
	State       sql.NullString
       # ... rest of the fields
}
```

However generated struct for my query doesn't contain mentioned tag;

```go
type FindAccountByEmailRow struct {
	ID           uuid.UUID
	State        sql.NullString
       # ... rest of the fields
}
```
When I use option:  ` emit_json_tags: true` I can see json tag in both places

So my question is if this is a problem or if the generator needs to be configured differently.

### Database schema

```sql
CREATE TABLE public.accounts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    state character varying,
);
```

### SQL queries

```sql
-- name: FindAccountByEmail :one
SELECT
    c.id AS credential_id,
    a.*,
    u.first_name,
    u.last_name,
    -- other fields
FROM
    accounts a
    INNER JOIN users_accounts ua ON a.id = ua.account_id
    INNER JOIN users u ON ua.user_id = u.id
    INNER JOIN credentials c ON c.account_id = a.id
WHERE
    c.email = @email;
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "db/structure.sql"
    queries: "db/queries.sql"
    engine: "postgresql"
    gen:
      go:
        package: "db"
        out: "db"
        overrides:
          - column: accounts.id
            go_struct_tag: sometagtype:"some_value"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
