### ISSUE TITLE
Override do not change bigint value to custom

### ISSUE THREAD

**Issue by DOOMKEKER** [kyleconroy/sqlc#1868]
### Version

1.15.0

### What happened?

In the configuration file there is an override for types, for text and for bigint, but bigint does not change to null.Int, and the text type changes. 

UPD.
Also it didn't work for all int vales.

``` go
type GetUserDetailsAdminRow struct {
	FirstName         null.String
	TG                IDsql.NullInt64
}
```

### Database schema

```sql
CREATE TABLE app_users.app_user (
    tg_id bigint,
    first_name text,
);
```

### SQL queries

```sql
SELECT au.first_name                             AS "firstName"
		 , au.tg_id                      AS "TGID"
	WHERE au.id = $1;
```

### Configuration

```yaml
version: "2"
sql:
- schema: [ "postgresql/cb_schema.sql", "postgresql/migrations" ]
  queries: ["postgresql/cb_query.sql", "postgresql/cb_admin_query.sql"]
  engine: "postgresql"
  gen:
    go:
      package: "db"
      out: "src/pgdb"
      sql_package: "pgx/v4"
      emit_db_tags: true
      emit_json_tags: true
      emit_empty_slices: true
      json_tags_case_style: "camel"
      overrides:
        - db_type: "bigint"
          nullable: true
          go_type: "github.com/guregu/null.Int"

        - db_type: "text"
          nullable: true
          go_type: "github.com/guregu/null.String"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
