### ISSUE TITLE
Singularizing "Meta" Error

### ISSUE THREAD

**Issue by jmillerv** [kyleconroy/sqlc#1892]
### Version

1.15.0

### What happened?

I have a table called items_meta. When sqlc goes to make the struct the logic that attempts to make idiomatic go translates it to `type TableItemsMetum struct`. While this is usable that isn't, according to any reading I can find, an appropriate way to "singularize" that. Is sqlc applying the rules for data/datum to words that end in `a`? 

### Database schema

```sql
CREATE TABLE bazaar.items_meta (
                                   id uuid NOT NULL DEFAULT uuid_generate_v4(), -- primary key
                                   items_id uuid NOT NULL, -- foreign key to items.id
                                   location_found varchar NULL,
                                   identified bool NULL DEFAULT false,
                                   created_date date NULL DEFAULT now(),
                                   updated_date date NULL DEFAULT now(),
                                   notes varchar NULL, -- additional information about the item
                                   invested bool NULL DEFAULT false,
                                   CONSTRAINT items_meta_pk PRIMARY KEY (id)
);
```

### Configuration

```yaml
version: 2
sql:
  - engine: "postgresql"
    schema: "schema.sql"
    queries: "query.sql"
    gen:
      go:
        package: "psql"
        out: "psql"
        emit_json_tags: true
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
