### ISSUE TITLE
sqlc.narg does not work with `strict_function_checks` enabled

### ISSUE THREAD

**Issue by brlala** [kyleconroy/sqlc#1900]
### Version

1.15.0

### What happened?

sqlc.narg does not work with `strict_function_checks` enabled, it throws an error saying `narg` function not found

### Database schema

```sql
CREATE TABLE foo (bar text not null, maybe_bar text);
```

### SQL queries

```sql
-- name: IdentOnNullable :one
SELECT maybe_bar FROM foo WHERE maybe_bar = sqlc.narg(maybe_bar);
```

### Configuration

```yaml
- schema: "query.sql"
    queries: "query.sql"
    engine: "postgresql"
    strict_function_checks: true
    gen:
      go:
        package: "querytest"
        out: "./"
        sql_package: "pgx/v4"
        emit_prepared_queries: true
        emit_json_tags: true
        emit_db_tags: true
        json_tags_case_style: snake
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
