### ISSUE TITLE
Rename Not Functioning

### ISSUE THREAD

**Issue by GoodiesHQ** [kyleconroy/sqlc#1926]
### Version

1.15.0

### What happened?

Renaming columns using version 2 of the configuration does not seem to work. Running `sqlc generate` after setting the desired rename values does not create structs with the proper names.

### Relevant log output

```shell
type Interface struct {
    ID           int64
    IpAddress    string
    Endpoint     string
    ListenPort   int64
    PrivateKey   string
    PublicKey    string
    Dns          string
    SearchDomain string
    Mtu          int64
    FwMark       int64
}
```

### Database schema

```sql
-- interfaces contain global settings that apply to either clients or server connections
CREATE TABLE Interfaces (
    id BIGINT PRIMARY KEY AUTOINCREMENT, -- identifier
    ip_address VARCHAR(255) NOT NULL, -- ip
    endpoint VARCHAR(255) NOT NULL DEFAULT '', -- remote ip or fqdn
    listen_port INTEGER NOT NULL DEFAULT 0, -- local port to listen on
    private_key VARCHAR(50) NOT NULL DEFAULT '', -- private portion of the key
    public_key VARCHAR(50) NOT NULL, -- public portion of the key
    dns VARCHAR(255) NOT NULL DEFAULT '', -- dns server (ips)
    search_domain VARCHAR(255) NOT NULL DEFAULT '', -- local search domain
    mtu INTEGER NOT NULL DEFAULT 0, -- maximum transmission unit
    fw_mark INTEGER NOT NULL DEFAULT 0 -- for iptables
);
```

### Configuration

```yaml
version: 2
sql:
- schema: "schema.sql"
  queries: "queries.sql"
  engine: "sqlite"
  gen:
    go:
      package: "db"
      out: "wvg/db"
      rename:
        dns: "DNS"
        mtu: "MTU"
        ip_address: "IPAddress"
```

### What operating system are you using?

macOS

### What type of code are you generating?

Go

**Comment by GoodiesHQ** [comment]
Duplicate.

For anyone looking, the correct syntax for version 2 should be:

```
version: 2
sql:
- schema: "schema.sql"
  queries: "queries.sql"
  engine: "sqlite"
  gen:
    go:
      package: "db"
      out: "wvg/db"
overrides:
  go:
    rename:
      dns: "DNS"
      mtu: "MTU"
      ip_address: "IPAddress"
```
