### ISSUE TITLE
To check if batch is closed if you need to return a pointer to the type the wrong code is generated

### ISSUE THREAD

**Issue by FlymeDllVa** [kyleconroy/sqlc#1959]
### Version

`v1.16.0` or 3623ec87fd3015f00cdc9e2c29c45d5557a12473, version `v1.15.0` has the correct behavior, since there is no batch closeness check

### What happened?

To check if batch is closed if you need to return a pointer to the type the wrong code is generated

<img width="435" alt="Screenshot 2022-11-19 at 17 39 42" src="https://user-images.githubusercontent.com/33265875/202856606-d0d69cb4-4bde-4fab-94a5-1bc83a3dcb06.png">

### SQL queries

```sql
:batchone
```

### Configuration

```yaml
version: "2"
engine: "postgresql"
sql_package: "pgx/v4"
emit_db_tags: true
emit_result_struct_pointers: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
