### ISSUE TITLE
JSONB with pgx v5

### ISSUE THREAD

**Issue by weeco** [kyleconroy/sqlc#1970]
### Version

Other

### What happened?

I'm using sqlc @c8c0233 , which is the latest version on master as of writing this article. I'm eager to use pgx v5, but I'm hitting an issue for an insert query that has JSONB (see below log output). 

### Relevant log output

```shell
2022-11-27T18:24:34.561Z        ERROR   ___API.server.postgres  tracelog/tracelog.go:302        Query   {"time": "39.254901ms", "pid": 3276650359, "sql": "-- name: CreateCluster :one\nINSERT INTO cluster (\n    id, organization_id, name, tags, status, region, max_sustained_throughput_bytes, created_at, updated_at, deleted_at\n) VALUES (\n    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?\n)\nRETURNING id, organization_id, name, tags, status, region, max_sustained_throughput_bytes, created_at, updated_at, deleted_at\n", "args": ["ce1qmolmk1u1d3d98fh0","9m4e2mr0ui3e8a215n4g","martins-cluster","7b22637265617465645f6174223a22323032322d4e6f762d3237222c2263726561746f72223a226d617274696e227d","7b7d","europe-west1",125000,"2022-11-27T18:24:34.521912Z",null,null], "err": "ERROR: syntax error at or near \",\" (SQLSTATE 42601)"}
```

### Database schema

```sql
CREATE TABLE cluster (
    id text NOT NULL,
    organization_id text NOT NULL,
    name text NOT NULL,
    tags jsonb,
    status jsonb NOT NULL,
    region text NOT NULL,
    max_sustained_throughput_bytes bigint NOT NULL,

    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    deleted_at timestamptz,
    PRIMARY KEY (id)
);
```

### SQL queries

```sql
-- name: CreateCluster :one
INSERT INTO cluster (
    id, organization_id, name, tags, status, region, max_sustained_throughput_bytes, created_at, updated_at, deleted_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING *;
```

### Configuration

```yaml
version: 2
sql:
  - engine: "postgresql"
    queries: "internal/storage/queries"
    schema: "internal/storage/migrations"
    gen:
      go:
        package: "gen"
        out: "internal/storage/gen"
        sql_package: "pgx/v5"
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        overrides:
          - column: cluster.id
            go_type: github.com/rs/xid.ID
          - column: cluster.organization_id
            go_type: github.com/rs/xid.ID
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by weeco** [comment]
When I try to run the SQL command as printed in the log output manually, the editor  flags the serialized JSON payload. It expects me to set a JSON payload rather than the serialized byte array I believe. 

This is the go code I use when calling the CreateCluster method:

```go
    clusterTags, err := json.Marshal(toCreate.Tags)
    if err != nil {
        return nil, fmt.Errorf("failed to marshal tags: %w", err)
    }

    createClusterParams := &storagegen.CreateClusterParams{
        ID:                          xid.New(),
        OrganizationID:              orgID,
        Name:                        toCreate.Name,
        Tags:                        clusterTags,
        Status:                      status,
        Region:                      toCreate.Region,
        MaxSustainedThroughputBytes: toCreate.MaxSustainedThroughputBytes,
        CreatedAt:                   pgtype.Timestamptz{Time: time.Now(), Valid: true},
        UpdatedAt:                   pgtype.Timestamptz{},
        DeletedAt:                   pgtype.Timestamptz{},
    }

    createdCluster, err := p.queries.CreateCluster(ctx, createClusterParams)
```

**Comment by mcdoker18** [comment]
I think your query doesn't work in pgxv4 too. I believe you should replace the query params with '$1, $2, $3, $4, $5, $6, $7, $8, $9, $10' .

By the way, pgx v5 can marshall to json automatically https://github.com/kyleconroy/sqlc/blob/main/docs/reference/datatypes.md#json

**Comment by weeco** [comment]
Thanks @mcdoker18 , super helpful feedback! I adapted the queries accordingly. Unfortunately I was not able to test it yet, because of one remaining issue:

I have one pointer type where the pkgname is different than the import path, so I tried to use this override:

```yaml
          - column: cluster.status
            go_type:
              import: "github.com/weeco/web-boilerplate/backend/internal/protogen/boilerplate/api/v1"
              package: "apiv1"
              type: "*ClusterStatus"
```

This throws the following error when trying to generate the code with SQLC:

> # package gen
error generating code: source error: 29:16: expected 'IDENT', found '*' (and 1 more errors)
Error: errored
errored
task: Failed to run task "backend:sqlc:generate": exit status 1

As soon as I remove the `*` it works just fine. It also works with `go_type` but in this specific case I can't use go_type because the import path is different than the pkg name unfortunately. Do you have an advice?

**Comment by mcdoker18** [comment]
```yaml
  - column: cluster.status
            go_type:
              import: "github.com/weeco/web-boilerplate/backend/internal/protogen/boilerplate/api/v1"
              package: "apiv1"
              type: "ClusterStatus"
              pointer: true
```
