### ISSUE TITLE
Custom struct doesn't affect queries model

### ISSUE THREAD

**Issue by Ahmad940** [kyleconroy/sqlc#1980]
### Version

1.15.0

### What happened?

```
    overrides:
      # over columns

      # user
      - column: users.password
        go_struct_tag: 'json:"-"'
      - column: users.session
        go_struct_tag: 'json:"-"'
      - column: users.first_name
        go_struct_tag: 'validate:"required"'
      - column: users.first_name
        go_struct_tag: 'validate:"required"'
```

the above override sqlc configuration only applies to struct in sqlc auto generated `models.go`, however it doesn't affect / apply to queires genereted code such as generated user.sql.go for example.

I'm i doing something wrong ? or this is the default behavior, if it is how to i make custom struct work with generated queries files model such as

```

const updateUser = `-- name: UpdateUser :one
UPDATE "users"
SET first_name  = $2,
    middle_name = $3,
    last_name   = $4,
    updated_at = NOW()
where mid = $1 RETURNING id, mid, first_name, middle_name, last_name, email, phone, profile_img, profile_img_id, password, verified, suspended, tos, role, session, balance, deleted, created_at, updated_at, developer
`

type UpdateUserParams struct {
	Mid        string      `json:"mid"`
	FirstName  string      `json:"first_name"`
	MiddleName null.String `json:"middle_name"`
	LastName   string      `json:"last_name"`
}
....
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
