### ISSUE TITLE
Column overrides have no effect when using SQLite engine

### ISSUE THREAD

**Issue by gregoryjjb** [kyleconroy/sqlc#1985]
### Version

1.15.0

### What happened?

Type overrides specified by column name have no effect when using SQLite as the engine. The same config works with MySQL. 

Check out the UUID column in the following playgrounds (snippets pasted below as well):

[SQLite playground showing bugged result](https://play.sqlc.dev/p/2c63b17ce6f6fe25e987ef9af4175641d1c9d3607be33cf4a86188b08a09f4dd)

[MySQL playground showing desired result](https://play.sqlc.dev/p/e4c0eb4fea3727afcaa38a584f8a507bb12b7d5f9e7f8e2159b5b5b9dc369b79)

The resulting struct with SQLite (no type override applied, it uses the default `sql.NullString`):
```go
type Author struct {
	ID   int64
	Name string
	Uuid sql.NullString
}
```

And with MySQL (it used UUID this time correctly):
```go
type Author struct {
	ID   int32
	Name string
	Uuid uuid.UUID
}
```

### Database schema

```sql
CREATE TABLE authors (
  id   INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  uuid TEXT
);
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ],
  "overrides": [
    {
      "column": "authors.uuid",
      "go_type": "github.com/gofrs/uuid.UUID",
      "nullable": true
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/2c63b17ce6f6fe25e987ef9af4175641d1c9d3607be33cf4a86188b08a09f4dd

### What operating system are you using?

Windows

### What type of code are you generating?

Go

**Comment by Edholm** [comment]
For those of you that want a "workaround", you need to explicitly specify the schema in the column override:

```yaml
        overrides:
          - column: "main.mytable.mycolumn"
            go_type: "github.com/gofrs/uuid.UUID"

```

This worked for me on sqlc v1.17.0.
