### ISSUE TITLE
Go EmitPointersForNullTypes don't work in config v2

### ISSUE THREAD

**Issue by mvrhov** [kyleconroy/sqlc#1989]
### Version

1.15.0

### What happened?

Ruining 1.16 I'm trying to port config to v2, however it seems that not all config options are supported in v2. Running sqlc generate results in 

```
error parsing sqlc.yaml: yaml: unmarshal errors:
  line 23: field emit_pointers_for_null_types not found in type config.SQLGo
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "./cmd/store/migrations/schema/"
    queries: "./cmd/store/migrations/query/"
    engine: "postgresql"
    gen:
      go:
        package: "gensql"
        out: "pkg/gensql"
        sql_package: "pgx/v5"
        emit_db_tags: false
        emit_prepared_queries: false
        emit_interface: false
        emit_exact_table_names: true
        emit_empty_slices: false
        emit_exported_queries: false
        emit_json_tags: false
        emit_result_struct_pointers: true
        emit_params_struct_pointers: true
        emit_methods_with_db_argument: true
        emit_enum_valid_method: false
        emit_all_enum_values: true
        emit_pointers_for_null_types: true
        json_tags_case_style: "none"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
