### ISSUE TITLE
SQLC generated files do not pass errcheck checks

### ISSUE THREAD

**Issue by Kilio22** [kyleconroy/sqlc#2014]
### Version

1.16.0

### What happened?

When running `errcheck` on files generated by sqlc (https://github.com/kisielk/errcheck), the following line makes the check fail:
```go
	defer rows.Close()
```
Here's the code generated:
```go
	rows, err := q.db.QueryContext(ctx, ..., arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close() // this line

        ...

	if err := rows.Close(); err != nil { // Why do we have the same line here?
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
```

It would be nice to change the way this line is generated (or even to remove it, as `rows.Close()` is called at the end of the code) to make it `errcheck` compliant.

### SQL queries

```sql
SELECT *
FROM organizations
ORDER BY name
OFFSET $1 LIMIT $2;
```

### Configuration

```yaml
version: 1
packages:
  - path: "app/sqlc"
    name: "sqlc"
    engine: "postgresql"
    schema: "./app/sqlc/schemas/"
    queries: "./app/sqlc/queries/"
    emit_json_tags: true
    emit_interface: true
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
