### ISSUE TITLE
Renamed column does not exist

### ISSUE THREAD

**Issue by bsiegert** [kyleconroy/sqlc#2022]
### Version

1.16.0

### What happened?

Apologies if this is a beginner's mistake.

I have a query for searching two concatenated field. For example, the search string `%ang/g` would match category = `lang/', dir='go'.

However, sqlc fails to generate code because there is no "name" field in the schema. There *is* a "name" field however, it is the result of the concatenation expression. I would have expected sqlc to generate a method that takes a parameter `name string`.

I tried using a named parameter like

`WHERE name LIKE @name::text`

but that results in a parse error:

```
line 18:21 no viable alternative at input ';\n\n-- name: GetAllPkgs :many\nSELECT category || dir AS name\nFROM pkgs\nWHERE name LIKE @name:'
line 18:21 no viable alternative at input 'LIKE @name:'
# package ddao
queries.sql:1:1: no viable alternative at input 'LIKE @name:'
```

### Relevant log output

```shell
# package db
query.sql:9:1: column "name" does not exist
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS pkgs (
    pkg_id INTEGER PRIMARY KEY ASC,
    category text NOT NULL,
    dir text NOT NULL,
    UNIQUE (category, dir)
);
```

### SQL queries

```sql
-- name: GetAllPkgs :many
SELECT category || dir AS name
FROM pkgs
WHERE name LIKE ?
ORDER BY name;
```

### Configuration

```yaml
version: 2
project:
    id: "github/com/bsiegert/BulkTracker"
sql:
    - engine: sqlite
      schema: schema.sql
      queries: queries.sql
      gen:
          go:
              package: ddao
              out: ddao
```

### Playground URL

https://play.sqlc.dev/p/50a7d3bc881d988a539d6f258f43c7365bbdcd5711791592102e70cd47670e59

### What operating system are you using?

Linux

### What type of code are you generating?

Go
