### ISSUE TITLE
use member of replace where in get syntax error

### ISSUE THREAD

**Issue by silver-brother** [kyleconroy/sqlc#2030]
### Version

1.16.0

### What happened?

In mysql, I want to use member of syntax instead of where in syntax, but I encounter a compile error

### Relevant log output

```shell
syntax error near "member of (?);"
```

### Database schema

```sql
CREATE TABLE `song` (
  `id` varchar(64) NOT NULL DEFAULT '',
  `create_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `update_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
  `name` varchar(256) NOT NULL DEFAULT '' COMMENT ' 歌曲名称 。 ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

### SQL queries

```sql
-- name: ListSongByIDS :many
SELECT *
FROM song
where id member of (?);
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "./schema"
    queries: "./queries"
    engine: "mysql"
    gen:
      go:
        package: "model"
        out: "model"
```

### Playground URL

https://play.sqlc.dev/p/8f37ba937f2e300b40fca209d3aaa88abe441855fb8c3fd52dd0d6b5df25196a

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
