### ISSUE TITLE
Problem to insert field JSONB

### ISSUE THREAD

**Issue by Tomelin** [kyleconroy/sqlc#2036]
### Version

1.16.0

### What happened?

I have the struct and the properties fields is JSONB type.  When I'll register new object in DB return the error **cannot encode status undefined**..

My struct is:
```
type EntityDefaultField struct {
	ID          tuuid.ID               `json:"id"`
	Name        string                 `json:"name" binding:"required"`
	Description string                 `json:"description"`
	Tag         string                 `json:"tag" binding:"required"`
	Properties  map[string]interface{} `type:"jsonb" json:"properties"`
	CreatedAt   string                 `json:"created_at"`
	UpdatedAt   string                 `json:"updated_at"`
	DeletedAt   string                 `json:"deleted_at"`
}
```

### Relevant log output

```shell
cannot encode status undefined
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS organization (
  id varchar(36) NOT NULL UNIQUE PRIMARY KEY,
  name varchar(255) NOT NULL UNIQUE,
  description varchar,
  properties jsonb,
  tag varchar(255) NOT NULL UNIQUE,
  "created_at" varchar,
  "updated_at" varchar NOT NULL,
  "deleted_at" varchar
);
```

### SQL queries

```sql
INSERT INTO organization (
  id, name, description, tag, created_at, updated_at, properties
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING *;
```

### Configuration

```yaml
---
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        emit_json_tags: true
        sql_package: "pgx/v4"
        package: "dbsql"
        out: "../../dbsql"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
