### ISSUE TITLE
Duplicate generated models when using shared migrations

### ISSUE THREAD

**Issue by Adibov** [kyleconroy/sqlc#2071]
### Version

1.15.0

### What happened?

In my project, I have multiple entities for my database and each of them has its own series of queries:
![image](https://user-images.githubusercontent.com/73794293/218732761-438500f7-9ec9-469c-87cb-5964d425412e.png)

Also, all of them are using the same set of migrations since as I know, _sqlc_ doesn't support migrating my database and is just generating queries, Therefor I need these migrations to be in the same place so I can manage them using another package (to be more precise, [this](github.com/golang-migrate/migrate) package).

But the problem is that when I place the migrations in one place, a few are duplicated when trying to generate files. More formally, `models.go` and `db.go` files are duplicated and have same contents. Is there any solution to overcome this behavior?

Thanks in advance

### Configuration

```yaml
version: "1"
packages:
  - name: "callers"
    path: "./entities/callers"
    queries: "./entities/callers/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "conditions"
    path: "./entities/conditions"
    queries: "./entities/conditions/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "eventsources"
    path: "./entities/eventsources"
    queries: "./entities/eventsources/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "eventtargets"
    path: "./entities/eventtargets"
    queries: "./entities/eventtargets/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true
  - name: "eventtargets"
    path: "./entities/eventtargets"
    queries: "./entities/eventtargets/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "experiments"
    path: "./entities/experiments"
    queries: "./entities/experiments/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "experimentselections"
    path: "./entities/experimentselections"
    queries: "./entities/experimentselections/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "flags"
    path: "./entities/flags"
    queries: "./entities/flags/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "layers"
    path: "./entities/layers"
    queries: "./entities/layers/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "overrides"
    path: "./entities/overrides"
    queries: "./entities/overrides/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "servicers"
    path: "./entities/servicers"
    queries: "./entities/servicers/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

  - name: "services"
    path: "./entities/services"
    queries: "./entities/services/queries"
    schema: "./migrations"
    engine: "postgresql"
    emit_json_tags: false
    emit_interface: true

overrides:
  - go_type: "github.com/jackc/pgtype.UUID"
    db_type: "uuid"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
