### ISSUE TITLE
Cannot override with standard library type

### ISSUE THREAD

**Issue by carlmjohnson** [kyleconroy/sqlc#2073]
### Version

Other

### What happened?

Trying to override a column to use a standard library type results in the error message:

```
error parsing sqlc.json: Package override `go_type` specifier "time.Time" is not the proper format, expected 'package.type', e.g. 'github.com/segmentio/ksuid.KSUID'
```

Workaround: instead of `"go_type": "time.Time"` use `"go_type": {"import":"time", "type": "Time"}`.

### Database schema

```sql
CREATE TABLE authors (
  birthday timestamptz not null
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT * FROM authors;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ],
  "overrides": [
    {
      "column": "author.birthday",
	  "go_type": "time.Time"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/e18cc29a5239b31fd32a651118f35b7f1b038b2e921644cec196290000867266

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
