### ISSUE TITLE
syntax error when using UNIQUE NULLS NOT DISTINCT

### ISSUE THREAD

**Issue by ehfeng** [kyleconroy/sqlc#2122]
### Version

1.16.0

### What happened?

You can follow the Getting Started on sqlc.dev. Then add this to your `schema.sql`:

```sql
CREATE TABLE person (
  first text,
  last text,
  unique nulls not distinct(first, last)
);
```

Then run `sqlc generate`.

### Relevant log output

```shell
"syntax error at or near "nulls"
```

### Database schema

```sql
CREATE TABLE person (
  first text,
  last text,
  unique nulls not distinct(first, last)
);
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "tutorial"
        out: "tutorial"
```

### Playground URL

https://play.sqlc.dev/p/0ab11ef7535e3bd78139602d4fd4599f9f8923130811a0510be2a52d192751a5

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
