### ISSUE TITLE
v1.17.2 Column override with imported go-type invalid when pointer:true

### ISSUE THREAD

**Issue by vmalyavin** [kyleconroy/sqlc#2125]
### Version

Other

### What happened?

When override table column with imported type as pointer  - type is not imports in queries.sql.go

### example
override with type `github.com/some/package/types.CustomTypeName` as pointer
https://play.sqlc.dev/p/ed5f9342ff8eda757c7bb8d1da9b27a94a734e2b98a6c8f73d08a10736ae9dae
```json
{
  "import": "github.com/some/package/types",
  "type": "CustomTypeName",
  "pointer": true
}
```
generates query.sql.go
without override type import:
```go
package model

import (
	"context"

	"github.com/google/uuid"
)
```
### valid example
same override without pointer flag
https://play.sqlc.dev/p/19de6fe73aa60dba17237db3f83530cf2ad3c4b8fb61c891b12ec3143496cff9
```json
{
  "import": "github.com/some/package/types",
  "type": "CustomTypeName"
}
```
generates query.sql.go
with valid import:
```go
package model

import (
	"context"

	"github.com/google/uuid"
	"github.com/some/package/types"
)
```

### Database schema

```sql
create table vendors
(
    id    uuid primary key,
    data jsonb
);
```

### SQL queries

```sql
/* name: GetVendors :one */
SELECT v.*, 'something' as custom FROM vendors v;
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [
    {
      "schema": "query.sql",
      "queries": "query.sql",
      "engine": "postgresql",
      "gen": {
        "go": {
          "package": "model",
          "out": "db",
          "overrides": [
            {
              "column": "vendors.data",
			  "go_type": {
			  	"import": "github.com/some/package/types",
				"type": "CustomTypeName",
				"pointer": true
			  },
              "nullable": true
            }
          ]
        }
      }
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/ed5f9342ff8eda757c7bb8d1da9b27a94a734e2b98a6c8f73d08a10736ae9dae

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
