### ISSUE TITLE
sqlc genarate - syntax error at or near ""

### ISSUE THREAD

**Issue by Bariyard** [kyleconroy/sqlc#2134]
### Version

1.17.2

### What happened?

run 
sqlc generate via CLI terminal

always got this response
syntax error at or near ""

```
- db
  - migration 
    - (migration file generated from golang-migrate)
  - query
    - (multiple.sql file here)
  - sqlc (out directory)
- sqlc.yaml
```

### Relevant log output

```shell
# package user-service
db/query/test.sql:1:1: syntax error at or near ""
```

### Database schema

```sql
CREATE TABLE "user" (
  "username" varchar PRIMARY KEY,
  "hashed_password" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now()),
  "modified_at" timestamptz NOT NULL DEFAULT (now())
);
```

### SQL queries

```sql
-- name: ListUsers :many
SELECT * FROM "user";
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "db/migration"
    queries: "db/query"
    engine: "postgresql"
    gen:
      go:
        package: "user-service"
        out: "db/sqlc"
        emit_json_tags: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go

**Comment by kyleconroy** [comment]
I believe the issue is your package name. In Go, package names can't contain dashes. Try this:

```yaml
version: "2"
sql:
  - schema: "db/migration"
    queries: "db/query"
    engine: "postgresql"
    gen:
      go:
        package: "user_service"
        out: "db/sqlc"
        emit_json_tags: true
```
