### ISSUE TITLE
Support needed for more fine-grained json tags

### ISSUE THREAD

**Issue by aliml92** [kyleconroy/sqlc#2145]
### What do you want to change?

The following configuration adds `json` tags for both model and `*Params`-like structs:
_**sqlc.yaml**_
```
version: "2"
sql:
  - engine: "postgresql"
    queries: "./db/query"
    schema: "./db/migration"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v4"
        out: "./db/sqlc"
        emit_interface: true                 
        emit_json_tags: true         # would've been great if this is split into two            
        emit_pointers_for_null_types: true
```
_**models.go**_
```
type Article struct {
	ID          uuid.UUID `json:"id"`
	AuthorID    uuid.UUID `json:"author_id"`
	Slug        string    `json:"slug"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Body        *string   `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
```
_**user.sql.go**_
```
const createUser = `-- name: CreateUser :one
INSERT INTO users (
    username,
    email,
    password 
) VALUES (
    $1,
    $2,
    $3
) 
RETURNING id, username, email, password, bio, image, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.Bio,
		&i.Image,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
```
Since we might not use `CreateUserParams` for request validation, it should be possible to not add `json` tags to such structs.

Is it possible to have something like the following:
 _**sqlc.yaml**_
```
version: "2"
sql:
  - engine: "postgresql"
    queries: "./db/query"
    schema: "./db/migration"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v4"
        out: "./db/sqlc"
        emit_interface: true                 
        emit_json_model_tags: true     # recommended 
        emit_json_param_tags: false   # recommended     
        emit_pointers_for_null_types: true
```
or
 _**sqlc.yaml**_
```
version: "2"
sql:
  - engine: "postgresql"
    queries: "./db/query"
    schema: "./db/migration"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v4"
        out: "./db/sqlc"
        emit_interface: true                 
        emit_json_tags: true     # leave as it is
        emit_json_param_tags: false   # recommended     
        emit_pointers_for_null_types: true
``` 

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go
