### ISSUE TITLE
sqlite: Type overriding with db_type depends on lettercase

### ISSUE THREAD

**Issue by abekoh** [kyleconroy/sqlc#2159]
### Version

1.17.2

### What happened?

When configure type overriding with `db_type`, results depend on schema's lettercase. It is successful only when it matches exactly.

generated model:
```go
type Example struct {
	ID        int64
	Lowertext *string
	Uppertext sql.NullString
	Lowerint  sql.NullInt64
	Upperint  *int
}
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE example
(
    id    INTEGER PRIMARY KEY,
    lowerText text,
    upperText TEXT,
    lowerInt integer,
    upperInt INTEGER
);
```

### Configuration

```yaml
{
  "version": "2",
  "sql": [
    {
      "engine": "sqlite",
      "schema": "query.sql",
      "queries": "query.sql",
      "gen": {
        "go": {
          "package": "db",
          "out": "db",
          "overrides": [
            {
              "db_type": "text",
              "go_type": {
                "type": "string",
                "pointer": true
              },
              "nullable": true
            },
            {
              "db_type": "INTEGER",
              "go_type": {
                "type": "int",
                "pointer": true
              },
              "nullable": true
            }
          ]
        }
      }
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/36a7d6747d55b6fc84a3815526173dbafabe31099f793f17491f3076c3ec74dd

### What operating system are you using?

macOS

### What type of code are you generating?

Go
