### ISSUE TITLE
When using type overrides with pointer true import are missing

### ISSUE THREAD

**Issue by ludusrusso** [kyleconroy/sqlc#2168]
### Version

1.17.2

### What happened?

In version 1.17.x, when using type overrides with something like that:

```
"go_type": {
          "import": "test",
		  "type": "Test",
		  "package": "t",
		  "pointer": true // <- here is the problem
        }
```

The output does not contain the import

```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

// missing import
import ()

type Author struct {
	ID   int64
	Name string
	Test *t.Test
}
```

### Relevant log output

```shell
N/A
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  name text      NOT NULL,
  test jsonb
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql",
	  "overrides": [
	  {
	  	"column": "authors.test",
		"go_type": {
          "import": "test",
		  "type": "Test",
		  "package": "t",
		  "pointer": true
        }
	  }
	  ]
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/0e968f5100c6326cf6a4b10baf3d45db7ebe0997f09d7bf03f2897f5e2553966

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
