### ISSUE TITLE
Moved postgres enums between schemas, sqlc replaces Go string types with interface{}

### ISSUE THREAD

**Issue by dseravalli** [kyleconroy/sqlc#2176]
### Version

1.17.2

### What happened?

I ran a migration on our Postgres 14.5 databse to move enum types between schemas using `SET SCHEMA`, and then updated the relevent tables. `sqlc generate` then replaces the previously correct string types with `interface{}`

This:
```go
type UpdateUserParams struct {
        ... other fields ...
	RoleType       RoleTypes
}
```

Becomes this:
```go
type UpdateUserParams struct {
        ... other fields ...
	RoleType       interface{}
}
```

### Database schema

```sql
ALTER TYPE role_types SET SCHEMA core;
ALTER TABLE core.users ALTER COLUMN role_type TYPE core.role_types;
```

### SQL queries

```sql
-- name: UpdateUser :exec
UPDATE core.users
SET first_name = $2,
  last_name = $3,
  bio = $4,
  city = $5,
  state = $6,
  country = $7,
  profile_image_id = $8,
  role_type = $9
WHERE Id = $1;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "sqlc/"
    schema: "./../../../db/sql/versioned-migrations/init"
    gen:
      go:
        sql_package: "pgx/v4"
        package: "db"
        out: "db"
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
