### ISSUE TITLE
ANY returning Empty Slice []

### ISSUE THREAD

**Issue by DarkHeros09** [kyleconroy/sqlc#2199]
### Version

1.17.2

### What happened?

the query returns empty slice when it should return a list of rows.

### Relevant log output

```shell
Should NOT be empty, but was []
```

### Database schema

```sql
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY
);
```

### SQL queries

```sql
-- name: ListProductItemsByIDs :many
SELECT * FROM "product_item"
WHERE id = ANY(sqlc.arg(products_ids)::bigint[]);
```

### Configuration

```yaml
version: "2"
sql:
- schema: "./db/migration/"
  queries: "./db/query/"
  engine: "postgresql"
  gen:
    go:
      package: "db"
      out: "./db/sqlc"
      sql_package: "pgx/v4"
      emit_prepared_queries: false
      emit_interface: true
      emit_exact_table_names: false
      emit_empty_slices: true
      emit_json_tags: true
      overrides:
        - db_type: "pg_catalog.int8"
          go_type: "github.com/guregu/null.Int"
          nullable: true

        - db_type: "bigserial"
          go_type: "github.com/guregu/null.Int"
          nullable: true

        - db_type: "pg_catalog.int4"
          go_type: "github.com/guregu/null.Int"
          nullable: true

        - db_type: "pg_catalog.varchar"
          go_type: "github.com/guregu/null.String"
          nullable: true

        - db_type: "timestamptz"
          go_type: "github.com/guregu/null.Time"
          nullable: true

        - db_type: "pg_catalog.bool"
          go_type: "github.com/guregu/null.Bool"
          nullable: true

        - column: "product.search"
          go_type: "github.com/guregu/null.String"
          nullable: true
```

### Playground URL

https://play.sqlc.dev/p/e740cbb88456621284a2c2cb714b98264e83914d8929209be8c18d12b5876ebf

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
