### ISSUE TITLE
sqlc.slice not working

### ISSUE THREAD

**Issue by jarri-abidi** [kyleconroy/sqlc#2200]
### Version

1.17.2

### What happened?

After https://github.com/kyleconroy/sqlc/pull/1816 was merged, I was expecting this to work. Could someone help?

### Relevant log output

```shell
/query.sql:7:1: function "sqlc.slice" does not exist
```

### Database schema

```sql
CREATE TABLE authors (
  id   INT PRIMARY KEY,
  name VARCHAR(64)
);
```

### SQL queries

```sql
-- name: ListAuthors :many
SELECT * FROM authors WHERE name IN (sqlc.slice('name'));
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "mysql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/4fed4224a30bfe3cb2b92b73bba13fe9125650984839faca4af999f377b1d55c

### What operating system are you using?

macOS

### What database engines are you using?

MySQL

### What type of code are you generating?

Go
