### ISSUE TITLE
sqlc does not detect or create a new file on a project which is on a removable disk

### ISSUE THREAD

**Issue by DhansAL** [kyleconroy/sqlc#2208]
### Version

Other

### What happened?

Running `sqlc init` on a project which is on `/media` directory gives nothing and does not create a `sqlc.yaml` file. 
It even fails to detect an existing `sqlc.yaml` file if  `sqlc generate` is run.

My project is on a mountable disk and I wanted to use sqlc in it. My environment details are,
```
OS - Ubuntu 22.04.2 LTS
sqlc version - v1.17.0
folder path - /media/myproject
go version - go1.20.3 linux/amd64
```

However, it works fine if my project is on `~/ ` directory. 

### Relevant log output

```shell
no output
```

### Database schema

```sql
can be reproduced with any or no schema.
```

### SQL queries

```sql
can be any queires
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "./db/query/"
    schema: "./db/migration/"
    gen:
      go:
        package: "db"
        out: "db/sqlc"
        emit_json_tags: true
        emit_empty_slices: true
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
