### ISSUE TITLE
Failed to scan `pg_catalog.time` into `time.Time`

### ISSUE THREAD

**Issue by abekoh** [kyleconroy/sqlc#2212]
### Version

1.17.2

### What happened?

It seems that the time type in PostgreSQL is mapped to time.Time by default.
While this is not a problem during INSERT operations, it appears to cause an error when scanning during SELECT operations.

### Relevant log output

```shell
panic: sql: Scan error on column index 0, name "t1": unsupported Scan, storing driver.Value type string into type *time.Time
```

### Database schema

```sql
CREATE TABLE example (
  t1 time NOT NULL
);
```

### SQL queries

```sql
-- name: GetExample :one
SELECT * FROM example;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/c18f6a528a3ba7cb75f1a6dcc083df000a2ab8ac70004ed90d5c30c24497d199

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
