### ISSUE TITLE
Column type `time WITH TIME ZONE` fails to scan when using pgx

### ISSUE THREAD

**Issue by andrewmbenton** [kyleconroy/sqlc#2221]
### Version

1.17.2

### What happened?

Scan fails with pgx when the schema includes a column with type `time WITH TIME ZONE`. I would expect it not to fail.

### Relevant log output

```shell
can't scan into dest[0]: parsing time "18:59:48.190691+00" as "2006-01-02 15:04:05.999999999Z07": cannot parse "18:59:48.190691+00" as "2006"
```

### Database schema

```sql
CREATE TABLE IF NOT EXISTS examples (
    t time WITH TIME ZONE NOT NULL
);
```

### SQL queries

```sql
-- name: InsertExample :one
INSERT INTO examples (t)
VALUES ($1)
RETURNING *;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "schema.sql",
      "queries": "query.sql",
      "sql_package": "pgx/v5"
    }
  ]
}
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
