### ISSUE TITLE
Use standard UUID package instead of pgtype.UUID in pgx/v5

### ISSUE THREAD

**Issue by jamesleeht** [kyleconroy/sqlc#2246]
### What do you want to change?

https://github.com/kyleconroy/sqlc/blob/main/internal/codegen/golang/postgresql_type.go#L271-L274

From the above, it seems like pgtype.UUID is being used instead of the standard google uuid.UUID.

Is there a technical reason for this? Because the pgtype.UUID is hard to work with - it doesn't expose the `parseUUID` method publicly: 
https://github.com/jackc/pgx/blob/master/pgtype/uuid.go#L33

This makes the solution to parsing somewhat clunky - you have to call the Scan method to convert a UUID string to it somehow.

### What database engines need to be changed?

PostgreSQL

### What programming language backends need to be changed?

Go

**Comment by panthershark** [comment]
This looks like a regression. The[ docs still say that sqlc uses google uuid.UUID](https://docs.sqlc.dev/en/latest/reference/datatypes.html?highlight=uuid#uuids
) by default.


You can add the following to your config to tell sqlc to use the google uuid package. 

```yaml
  overrides:
    - go_type: "github.com/google/uuid.UUID"
      db_type: "uuid"
```

**Comment by Terrible59** [comment]
> This looks like a regression. The[ docs still say that sqlc uses google uuid.UUID](https://docs.sqlc.dev/en/latest/reference/datatypes.html?highlight=uuid#uuids) by default.
> 
> You can add the following to your config to tell sqlc to use the google uuid package.
> 
> ```yaml
>   overrides:
>     - go_type: "github.com/google/uuid.UUID"
>       db_type: "uuid"
> ```

Override won't work, here are the lines from source code:
`case "uuid":
		if driver == SQLDriverPGXV5 {
			return "pgtype.UUID"
		}
		if notNull {
			return "uuid.UUID"
		}
		if emitPointersForNull {
			return "*uuid.UUID"
		}
		return "uuid.NullUUID"`
		
The only solution right now is to override every DB column type to google's UUID

**Comment by markschmid** [comment]
Currently struggling with exactly the same problem.

**Comment by dx314** [comment]
Ditto

**Comment by markschmid** [comment]
I haven't looked much into it, but so far it seems to work for me using the following in sqlc.yaml (excerpt):

```
version: "2"
overrides:
  go:
    overrides:
      - db_type: "uuid"
        engine: "postgresql"
        go_type: "github.com/google/uuid.UUID"
```

Instead of pgtype.UUID it now uses Google's UUID type.

**Comment by sxwebdev** [comment]
@kyleconroy I try to reproduce your example and it doesn't work

https://play.sqlc.dev/p/45720eb1e3449cb7265315f78b06dc28e016077817b83469abd6d14eb777bacb

**Comment by sxwebdev** [comment]
I found the solution and it works now

https://play.sqlc.dev/p/19fd2d4e5e48be8282dc87d5bb291d32dab946e7b36fd561955ece18849405b2

```
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "query.sql"
    gen:
      go:
        package: "db"
        sql_package: "pgx/v5"
        out: "db"
overrides:
  go:
    overrides:
      - db_type: "uuid"
        go_type: "github.com/google/uuid.UUID"
      - db_type: "uuid"
        nullable: true
        go_type: "github.com/google/uuid.NullUUID"
```
