### ISSUE TITLE
sqlc not generating GoLang code

### ISSUE THREAD

**Issue by RipulHandoo** [kyleconroy/sqlc#2322]
### Version

1.18.0

### What happened?

PS C:\Users\HP\Desktop\go> sqlc generate
# package postgres
schema.sql:1:1: the PostgreSQL engine does not support Windows

### Relevant log output

```shell
PS C:\Users\HP\scratch> sqlc version
v1.18.0
PS C:\Users\HP\scratch> psql --version
psql (PostgreSQL) 15.3
PS C:\Users\HP\scratch> sqlc generate
# package database
sql\schema\001_users.sql:1:1: the PostgreSQL engine does not support Windows.
PS C:\Users\HP\scratch>
```

### Database schema

```sql
-- +goose Up

CREATE TABLE users (
    id UUID PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name TEXT NOT NULL
);

-- +goose Down
DROP TABLE users;
```

### SQL queries

```sql
-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, name)
VALUES($1,$2,$3,$4)
RETURNING *;
```

### Configuration

```yaml
version: "2"
sql:
  - schema: "sql/schema"
    queries: "sql/queries"
    engine: "postgresql"
    gen:
      go:
        out: "internal/database"
```

### What operating system are you using?

Windows

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
