### ISSUE TITLE
A recursive query with computed integer terms fails with a syntax error

### ISSUE THREAD

**Issue by ollie-williams** [kyleconroy/sqlc#2390]
### Version

1.18.0

### What happened?

I'm using Postgres's RECURSIVE subquery in order to compute an order walk of a tree-like data structure.

### Relevant log output

```shell
sqlc generate
# package db
query.sql:110:1: edited query syntax is invalid: syntax error at or near "FROM"
```

### Database schema

```sql
CREATE TABLE graphs (
    graph_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    author TEXT,
    script TEXT
);

CREATE TABLE nodes (
    node_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind Kind NOT NULL,
    name TEXT NOT NULL,
    graph UUID NOT NULL REFERENCES graphs(graph_id) ON DELETE CASCADE
);

CREATE TABLE edges (
    parent UUID REFERENCES nodes (node_id),
    child UUID REFERENCES nodes (node_id),
    ordinal INT NOT NULL,
    graph UUID NOT NULL REFERENCES graphs(graph_id) ON DELETE CASCADE,
    PRIMARY KEY(parent, child)
);
```

### SQL queries

```sql
-- name: GetDependentNodes :many
WITH RECURSIVE ds(id, depth) AS (
	SELECT parent AS id, 0
	FROM edges WHERE edges.child=$1
  UNION ALL
	SELECT edges.parent, depth+1
	FROM ds, edges WHERE edges.child=ds.id
)
SELECT * FROM ds ORDER BY depth;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "query.sql"
    schema: "schema.sql"
    gen:
      go:
        package: "db"
        out: "pkg/db"
        sql_package: "pgx/v5"
        emit_json_tags: true
        emit_result_struct_pointers: true
```

### What operating system are you using?

macOS

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
