### ISSUE TITLE
sqlc.embed breaks when using left outer join

### ISSUE THREAD

**Issue by vamshiaruru32** [kyleconroy/sqlc#2402]
### Version

1.18.0

### What happened?

Consider a query like this

```
-- name: LeftOuterJoin
SELECT sqlc.embed(A), sqlc.embed(B)
FROM A
LEFT OUTER JOIN B on A.id = B.aid;
```
This generates a struct like this
```go
type LeftOuterJoinRow struct {
    a A
    b B
}
```
But, this isn't correct, because b can be null. So when trying to scan, you'll get an error like:
```
panic: can't scan into dest[9]: cannot scan NULL into *int32
```
becuase the fields inside B are not marked as nullable.

PS: I apologize for not being able to submit a playground link. I am getting all sorts of errors trying to generate that link.

### Relevant log output

```shell
panic: can't scan into dest[9]: cannot scan NULL into *int32
```

### Database schema

```sql
CREATE TABLE A ( id SERIAL PRIMARY KEY );

CREATE TABLE B ( id SERIAL PRIMARY KEY, aid INTEGER REFERENCES A (id))
```

### SQL queries

```sql
SELECT sqlc.embed(A), sqlc.embed(B)
FROM A
LEFT OUTER JOIN B on A.id = B.aid;
```

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "remote/db/sqlc"
    schema: "remote/db/schema.sql"
    gen:
      go:
        package: "dao"
        out: "internal/dao"
        sql_package: "pgx/v5"
        emit_pointers_for_null_types: true
        emit_interface: true
        emit_json_tags: true
        overrides:
          - go_type:
              import: "github.com/glhf-labs/bastille/internal/models/core"
              package: "coremodels"
              type: "StrMap"
            db_type: "jsonb"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
