### ISSUE TITLE
Sqlc not generating prepared queries for postgres (pgx/v5)

### ISSUE THREAD

**Issue by vamshiaruru32** [kyleconroy/sqlc#2422]
### Version

1.18.0

### What happened?

I am using sqlc v1.19 but I can't see it in the verion dropdown. 

After setting  `emit_prepared_queries: true`, running sqlc --experimental generate doesn't emit prepared queries for postgres. It does it if you don't use pgx/v5 as sql package.

Any work around for this? Or am I missing something?

Thanks for the help.

### Configuration

```yaml
version: "2"
sql:
  - engine: "postgresql"
    queries: "remote/db/sqlc"
    schema: "remote/db/schema.sql"
    gen:
      go:
        package: "pgDao"
        out: "internal/dao/pg"
        sql_package: "pgx/v5"
        emit_prepared_queries: true
        emit_pointers_for_null_types: true
        emit_interface: true
        emit_json_tags: true
        overrides:
          - go_type:
              import: "github.com/glhf-labs/bastille/internal/models/core"
              package: "coremodels"
              type: "StrMap"
            db_type: "jsonb"
```

### What operating system are you using?

Linux

### What database engines are you using?

PostgreSQL

### What type of code are you generating?

Go
