### ISSUE TITLE
`sqlc.slice()` generates broken code when `emit_prepared_queries` is enabled

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [kyleconroy/sqlc#2430]
### Version

1.19.0

### What happened?

```
pkg/db/my_table.sql.go:95:35: not enough arguments in call to q.query
        have (context.Context, string, []interface{})
        want (context.Context, *sql.Stmt, string, ...interface{})
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  name text      NOT NULL,
  bio  text
);
```

### SQL queries

```sql
-- name: GetAuthorsBroken :many
SELECT * FROM authors
WHERE name in (sqlc.slice(names));
```

### Configuration

```yaml
version: 2
sql:
  - engine: "sqlite"
    schema: "pkg/db/migrations"
    queries: "pkg/db/queries"
    gen:
      go:
        emit_prepared_queries: true
        emit_db_tags: true
        package: "db"
```

### Playground URL

https://play.sqlc.dev/p/cc0e82b9bf323ca2a1d8de4cd5d5aedaca0b7aac8dc7dc3f0df4105fe2fcb07a

### What operating system are you using?

Linux

### What database engines are you using?

SQLite

### What type of code are you generating?

Go
