### ISSUE TITLE
Decimal columns output strings in generated models

### ISSUE THREAD

**Issue by blwsh** [kyleconroy/sqlc#2496]
### Version

1.19.1

### What happened?

Decimal mysql columns cast to strings in models.

Please see db/models.go in this playground for an example: https://play.sqlc.dev/p/f304fbebbc304d748911d58c99dbc1015a265472450e8d7ddf0b662d8268d660

### Relevant output

```go
// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package db

import (
	"database/sql"
)

type Author struct {
	ID              int64
	DecimalTest     sql.NullString
	DecimalTestTwo  string
	DecimalTestNull string
}
```

### Database schema

```sql
-- Example queries for sqlc
CREATE TABLE authors (
  id   BIGSERIAL PRIMARY KEY,
  decimal_test              decimal,
  decimal_test_two          decimal(9,2)            not null,
  decimal_test_null         decimal                 not null
);
```

### SQL queries

```sql
-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;
```

### Configuration

```yaml
{
  "version": "1",
  "packages": [
    {
      "path": "db",
      "engine": "postgresql",
      "schema": "query.sql",
      "queries": "query.sql"
    }
  ]
}
```

### Playground URL

https://play.sqlc.dev/p/f304fbebbc304d748911d58c99dbc1015a265472450e8d7ddf0b662d8268d660

### What database engines are you using?

* MySQL
* Postgress

### What type of code are you generating?

Go
