### ISSUE TITLE
Field `null` in Override configuration is ignored.

### ISSUE THREAD

**Issue by ipsusila** [kyleconroy/sqlc#413]
Hi, thank you for the nice software. I'm facing the following issue, in which the `overrides` settings was not applied properly.

When the configuration is:
```
overrides:
  - go_type: "sql.NullInt64"
    db_type: "integer"
    null: true
```
the `null` config value is not decoded properly. However, if I changed the configuration to (use `"null"` as field name)
```
overrides:
  - go_type: "sql.NullInt64"
    db_type: "integer"
    "null": true
```
`sqlc` will correctly override type as expected. In the former case, `YAML` decoder is failed to decode the configuration (the value is always `false`), perhaps because the field name is `null`.
Probably this issue is related to #412 too?
