### ISSUE TITLE
Support glob patterns in column name for overrides

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#418]
I have the following `sqlc.yaml` file in my project:

```yaml
version: "1"
packages:
  - path: db
    emit_prepared_queries: true
    schema: sql/schema.sql
    queries: sql/query.sql
overrides:
  - column: "organizations.id"
    go_type: "github.com/segmentio/ksuid.KSUID"
  - column: "projects.id"
    go_type: "github.com/segmentio/ksuid.KSUID"
  - column: "projects.organization_id"
    go_type: "github.com/segmentio/ksuid.KSUID"
```

It would be really nice If I could the following two lines to override all columns named `id` and all columns ending in `_id`.

```yaml
version: "1"
packages:
  - path: db
    emit_prepared_queries: true
    schema: sql/schema.sql
    queries: sql/query.sql
overrides:
  - column: "id"
    go_type: "github.com/segmentio/ksuid.KSUID"
  - column: "*_id"
    go_type: "github.com/segmentio/ksuid.KSUID"
```
