### ISSUE TITLE
unknown PostgreSQL type: pg_catalog.interval

### ISSUE THREAD

**Issue by carlmjohnson** [kyleconroy/sqlc#429]
Given this SQL:

```sql
-- name: Test :one
SELECT
  $1::interval;
```

I get this error: `2020/04/02 10:21:57 unknown PostgreSQL type: pg_catalog.interval`.

I believe there is some trickiness here because Go time.Duration and PostgreSQL interval have different ranges and precisions, but it would be nice to have an issue to track it one way or the other.

**Comment by kyleconroy** [comment]
> I believe there is some trickiness here because Go time.Duration and PostgreSQL interval have different ranges and precision

See the discussion in https://github.com/lib/pq/issues/78. Mapping between the two really isn't feasible. There are few packages out there that implement a compatible interval type. Adding the following to your sqlc.yaml / sqlc.json should fix your issue:

```yaml
overrides:
  - db_type: 'interval'
    go_type: 'github.com/jackc/pgtype.Interval'
  - db_type: 'interval'
    go_type: 'github.com/jackc/pgtype.NullInterval'
    "null": true
```
