### ISSUE TITLE
Add domain support

### ISSUE THREAD

**Issue by kyleconroy** [kyleconroy/sqlc#434]
A domain is "essentially a data type with optional constraints". You can think of them as type aliases. By using a domain, you can easily create custom types. For example, here's how you could create a KSUID type.

```sql
CREATE DOMAIN ksuid AS VARCHAR(27) NOT NULL;

CREATE TABLE foo (
    id ksuid PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE bar (
    id ksuid PRIMARY KEY,
    created_at TIMESTAMP DEFAULT NOW(),
    foo_id ksuid REFERENCES foo(id),
    name text NOT NULL,
    slug text NOT NULL UNIQUE
);
```

The advantage to using a domain is that you'd only need one entry in overrides

```yaml
overrides:
  - db_type: "ksuid"
    go_type: "github.com/segmentio/ksuid.KSUID"
```

Replaces #418
