### ISSUE TITLE
syntax error at or near "$"

### ISSUE THREAD

**Issue by Xeoncross** [kyleconroy/sqlc#454]
Copying the [25 line sample config](https://github.com/kyleconroy/sqlc#getting-started) exactly as shown, pasting it into a file, and running it with `sqlc compile` or `sqlc generate` leaves me with the following errors:

```
test.sql:9:15: syntax error at or near "$"
test.sql:8:1: failed to parse query leading comment
test.sql:19:5: syntax error at or near "$"
test.sql:20:1: syntax error at or near "2"
test.sql:25:14: syntax error at or near "$"
```

I tried with an `sqlc init` YAML file and the JSON file design in https://github.com/kyleconroy/sqlc/tree/master/examples/authors.

sqlc version: `v1.2.1-devel`

**Comment by kyleconroy** [comment]
I can't reproduce this locally.

```
$ tree test/
test/
├── sqlc.yaml
└── test.sql
```

```yaml
# sqlc.yaml
version: "1"
packages:
  - path: db
    schema: test.sql
    queries: test.sql
```

```sql
-- test.sql
CREATE TABLE authors (
          id   BIGSERIAL PRIMARY KEY,
          name text      NOT NULL,
          bio  text
);

-- name: GetAuthor :one
SELECT * FROM authors
WHERE id = $1 LIMIT 1;

-- name: ListAuthors :many
SELECT * FROM authors
ORDER BY name;

-- name: CreateAuthor :one
INSERT INTO authors (
          name, bio
) VALUES (
  $1, $2
)
RETURNING *;

-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1;
```

Running `sqlc generate` in the `test` directory outputs no errors. Can you double check that you copied the example SQL correctly?

**Comment by Xeoncross** [comment]
My mistake, with Postgres this works fine as you show. I had changed the engine to `mysql` and failed to take that into account considering this was a PGSQL first project.

```
version: "1"
packages:
  - path: db
    schema: test.sql
    queries: test.sql
    engine: mysql
```

Any idea what I need to do to get MySQL/MariaDB working? I'm going to go review the code more now.

**Comment by Xeoncross** [comment]
The following is the simplest example I can use:

test.sql
```
-- name: ListAuthors :many
SELECT * FROM authors;
```
sqlc.yml
```
version: "1"
packages:
  - path: db
    queries: test.sql
    engine: mysql
```

**Comment by kyleconroy** [comment]
If you're using MySQL, you need to use the `/* comment */` format.

```
/* name: ListAuthors :many */
SELECT * FROM authors;
```

Sorry for the poor state of the MySQL documentation.

**Comment by Xeoncross** [comment]
Still no luck, though it seems the SQL parser is happy now and it's something internal to sqlc.

```
/* name: ListAuthors :many */
SELECT * FROM authors;
```

```
version: "1"
packages:
  - path: db
    queries: test.sql
    engine: mysql
```

```
$ sqlc generate
error generating code: template: table:252:79: executing "queryCode" at <.Ret.Type>: error calling Type: no type for GoQueryValue:
```

**Comment by Xeoncross** [comment]
Returning to the full authors example above there is still a parse error with the placeholders.

test.sql
```
CREATE TABLE authors (
    id int(11) NOT NULL AUTO_INCREMENT,
    name text NOT NULL,
    bio  text
);

/* name: GetAuthor :one */
SELECT * FROM authors
WHERE id = $1 LIMIT 1;

/* name: ListAuthors :many */
SELECT * FROM authors
ORDER BY name;

/* name: CreateAuthor :one */
INSERT INTO authors (
          name, bio
) VALUES (
  $1, $2
)
RETURNING *;

/* name: DeleteAuthor :exec */
DELETE FROM authors
WHERE id = $1;
```

```
version: "1"
packages:
  - path: db
    queries: test.sql
    engine: mysql
```

```
$ sqlc generate
# package db
test.sql:10:15: syntax error at or near "$"
test.sql:20:5: syntax error at or near "$"
test.sql:21:1: syntax error at or near "2"
test.sql:26:14: syntax error at or near "$"
```
