### ISSUE TITLE
Fully qualified name to Go type not applied, no erros shown in console

### ISSUE THREAD

**Issue by Maxiride** [kyleconroy/sqlc#462]
Due to the heavy involvement of marshalling and unmarshalling to JSON needed in my application I wanted to use the _zero._ types provided by [gopkg.in/guregu/null.v3/zero](https://gopkg.in/guregu/null.v3/zero).

I've tried to do a test run to substitute strings with the _zero.String_ type provided by the package without success, here is the relevant configuration.

```
overrides:
  - go_type: "gopkg.in/guregu/null.v3/zero.String"
    db_type: "string"
    "null": true
```
I am using  `"null"` thanks to the report made in #413

The type applied to the generated models is still the default `sql.NullString`.

Given that I never heard of "fully qualified name to a go type" I suppose I might be wrong in the configuration 😅 and I'd appreciate to shed some light on the subject.

---
Upon further browsing the issue I found #255 which I suppose is related if not the same issue I am encountering.
