### ISSUE TITLE
Multi files for schema definition

### ISSUE THREAD

**Issue by flowHater** [kyleconroy/sqlc#536]
How can I register multiple files for the schemas definitions ?

I mean for exemple:
For my User Schema, I would Like:
`20200507212055-add-users-table.sql` with a `name` `email` `psswd`
`20200607212055-add-token-registration-to-user-table.sql` to add a new column to my user table etc..

This could be useful for migration purposes.

Thanks for this project. WP

**Comment by maxhawkins** [comment]
If you set your schema path to a folder that contains both files it will run them in alphabetical order like a migration. The tool also supports [rollback statements](https://github.com/kyleconroy/sqlc/blob/master/docs/migrations.md) supported by many common SQL migration tools.

Check out the [`ondeck`](https://github.com/kyleconroy/sqlc/tree/master/examples/ondeck) example which contains a schema with multiple sql files.

**Comment by kyleconroy** [comment]
As @maxhawkins mentioned, you can pass a path to a folder for schemas

```yaml
version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "./sql/query/"
    schema: "./sql/schema/"
    engine: "postgresql"
```

You can also pass multiple paths, if you have different directories or only want to include certain files

```
version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "./sql/query/"
    schema:
      - "./sql/schema/one.sql"
      - "./sql/schema/two.sql"
    engine: "postgresql"
```
