### ISSUE TITLE
Cannot override created type

### ISSUE THREAD

**Issue by warent** [kyleconroy/sqlc#661]
Something like this:
```sql
create type foo as enum {
    'bar'
};

create table demo {
     col foo
};
```

```yaml
version: "1"
overrides:
  - db_type: "foo"
    go_type: "github.com/gofrs/uuid.UUID"
```

```yaml
version: "1"
overrides:
  - column: "demo.col"
    go_type: "github.com/gofrs/uuid.UUID"
```

Neither config overrides. We still get the custom enum type.
