### ISSUE TITLE
How to delete a column

### ISSUE THREAD

**Issue by kevinburkemeter** [kyleconroy/sqlc#662]
Say I want to delete a column but the table has a `SELECT *` query. If I run the migration first, the code will fail because it's trying to read a column that no longer exists. But I can't update the code until I add/run the migration.

I have checks in place that 1) all migrations have been run before code is deployed and 2) generated sqlc code is up to date with what's in the migrations folder, so it's sort of tricky to do a shadow migration.

Is there a way to omit a column from the generated sqlc code used by `SELECT *, RETURNING *` expansion?

**Comment by kyleconroy** [comment]
I think I have an answer for you.

The `schema` property can take a list of paths. Create a second folder for pending migrations and put the migration that drops the column in that directory. sqlc will generate code without the column. You can deploy that code and then move the SQL file into the actual migrations folder.

```yaml
version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "queries"
    schema:
      - "migrations/current"
      - "migrations/shadow"
```
