### ISSUE TITLE
Stable Mysql Support

### ISSUE THREAD

**Issue by tooolbox** [kyleconroy/sqlc#664]
Hey there, awesome library!

I am wondering if there is any ETA for stable Mysql support.  Not because I am trying to put pressure on this, but since I can't afford to be bleeding-edge I would like to revisit this project once the Mysql support is more mature.

Is this something we will see in 2020, perhaps?  Thanks!

**Comment by kyleconroy** [comment]
Great question! MySQL is coming along nicely. As discussed in #150 and #633, the current mysql package is deprecated. However, don't fret. The new MySQL engine, code-named Dolphin, is available in beta. The next release (v1.6.0) will promote this engine to stable.

Please try out the new engine now! In your sqlc configuration file, use `mysql:beta` for your engine value. Please report any bugs or missing features.

```yaml
version: "1"
packages:
  - name: "db"
    path: "internal/db"
    queries: "./sql/query/"
    schema: "./sql/schema/"
    engine: "mysql:beta"
```
