### ISSUE TITLE
null overrides `timestamp` to `*time.Time` not working

### ISSUE THREAD

**Issue by mvrhov** [kyleconroy/sqlc#814]
I'm not sure and I might be missing something, but null overrides at least for `timestamp` to `*time.Time`, doesn't seem to wok, `text`, to *string works, `jsonb` to `*json.RawMessage`

I've also tried with `timestamptz, timestamp(0), timestamp without time zone` I'm unable to debug this as the go compiler fails when building debug version in Goland with OOM.. it seems that 8G of free ram is not enough.

```yaml
version: "1"
packages:
  - name: "db"
#....
overrides:
  - db_type: "timestamp"
    go_type:
      import: "time"
      package: "time"
      type: "Time"
      pointer: true
    nullable: true
  - db_type: "jsonb"
    go_type:
      import: "json"
      package: "json"
      type: "RawMessage"
      pointer: true
    nullable: true
```

```sql
CREATE TABLE office (
    id_office bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    created_at timestamp(0) DEFAULT now() NOT NULL,
    updated_at timestamp(0),
);

-- name: ListOffices :many
SELECT * FROM office
ORDER BY name;
```

This always generates

```go
type Office struct {
	IDOffice    int64
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
}
```

**Comment by mvrhov** [comment]
Meh.. this seems to somewhat work but it's tedious and almost impossible to guess.

```yaml
  - db_type: "pg_catalog.timestamp"
    go_type:
      import: "time"
      type: "Time"
      pointer: true
    nullable: true

  - db_type: "pg_catalog.int2"
    go_type:
      type: "int16"
      pointer: true
    nullable: true
  - db_type: "pg_catalog.int4"
    go_type:
      type: "int"
      pointer: true
    nullable: true
  - db_type: "pg_catalog.int8"
    go_type:
      type: "int64"
      pointer: true
    nullable: true
  - db_type: "pg_catalog.bool"
    go_type:
      type: "bool"
      pointer: true
    nullable: true
  - db_type: "pg_catalog.float4"
    go_type:
      type: "float32"
      pointer: true
    nullable: true
  - db_type: "pg_catalog.float8"
    go_type:
      type: "float64"
      pointer: true
    nullable: true
```

**Comment by jskelcy** [comment]
hmm I am trying to use this and its not working for me. Anything tricky you did here @mvrhov ?

**Comment by mvrhov** [comment]
@jskelcy Are you saying, that the config one post above your doesn't work for you?

**Comment by jskelcy** [comment]
I should have updated here. But I found my issue, essentially the `params` object which are generated for a function dont seem to respect overrides in some cases. The tables themselves were being generated with the right types. I was able to come up with a workaround, I outline it in sort of an exploratory stream of consciousness here: https://github.com/kyleconroy/sqlc/issues/950. I will be updating the ticket with a summary today.

Thanks for checking @mvrhov

**Comment by ptman** [comment]
I'm not having success with using `*string` instead of `NullString`:

```yaml
overrides:
  - db_type: 'pg_catalog.text'
    go_type:
      type: 'string'
      pointer: true
    nullable: true
  - db_type: 'pg_catalog.text'
    go_type:
      type: 'string'
      pointer: false
    nullable: false
```

**Comment by mvrhov** [comment]
` db_type: 'pg_catalog.text'` should be `- db_type: 'text'`. Yeah I know it's a mess and mix of both depending on the type.

**Comment by kyleconroy** [comment]
Tracking documentation improvements for this https://github.com/sqlc-dev/sqlc/issues/2762

**Comment by lightSoulDev** [comment]
This issue appears to be resolved in current versions, but since it remains open and is still discoverable through search engines. I wanted to summarize and document this workaround for anyone facing similar issues and suggest to close the issue if it is no longer relevant and this feature is already documented in the sqlc documentation.

## Issue
When using `emit_pointers_for_null_types: true` with type overrides in sqlc, nullable columns don't generate pointer types as expected for cerain types. For example: `pgtype.Timestamptz` is generated for nullable timestamptz fields.

## Solution
Adding an additional override entry with `db_type.nullable: true` and `go_type.pointer: true` resolved the issue:

```yaml
...
emit_pointers_for_null_types: true
overrides:
  - db_type: "timestamptz"
    go_type:
      import: "time"
      type: "Time"
  - db_type: "timestamptz"
    nullable: true
    go_type:
      import: "time"
      type: "Time"
      pointer: true
```

## Example

Given this SQL schema:
```sql
CREATE TABLE "user" (
    ...
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);
```

The generated Go struct now correctly uses pointer types for nullable fields:
```go
type User struct {
    ...
    CreatedAt time.Time   `json:"created_at"`
    DeletedAt *time.Time  `json:"deleted_at"`
}
```

Without the nullable override, `DeletedAt` would be generated as `pgtype.Timestamptz` instead of `*time.Time`.

```go
type User struct {
    ...
    CreatedAt time.Time           `json:"created_at"`
    DeletedAt pgtype.Timestamptz  `json:"deleted_at"` 
}
```
