### ISSUE TITLE
Mysql: Failed to Parse Aliased Table Name and Ignoring Parameters in Join Statements

### ISSUE THREAD

**Issue by kejith** [kyleconroy/sqlc#817]
Hello,

when trying to join a second table to the first one i keep stumbeling on some Issues. 

**When joining with a Subquery** 
```mysql
SELECT
	p.id,
        pv.user_id,
	pv.upvoted 
FROM
	posts p
	LEFT JOIN ( SELECT * FROM post_votes WHERE user_id = ? ) AS pv ON pv.post_id = p.id 
WHERE
	p.deleted_at IS NULL;
```

Result
```
failed to parse table name alias's: failed to parse AliasedTableExpr name: &{0xc000453890 [] pv <nil>}
```

**When doing the same thing with a standard JOIN**
```mysql
/* name: GetVotedPosts :many */
SELECT
	p.id,
        pv.user_id,
	pv.upvoted
FROM
	posts p
	LEFT JOIN post_votes AS pv ON pv.post_id = p.id 
	AND pv.user_id = ?
WHERE
	p.deleted_at IS NULL;
```

The generated Code **does not Implement a Parameter** i can call the function with 
```go
func (q *Queries) GetVotedPosts(ctx context.Context) ([]GetVotedPostsRow, error) {
	rows, err := q.db.QueryContext(ctx, getVotedPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVotedPostsRow{}
	for rows.Next() {
		var i GetVotedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Upvoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
```

**Schemas**
Post
```mysql
CREATE TABLE posts (
  /* keys */
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

  /* date */
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  deleted_at DATETIME DEFAULT NULL,

  /* body */  
  url TEXT NOT NULL,
  image VARCHAR(255) NOT NULL,

  /* foreign key*/
  user_name VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE posts
  ADD FOREIGN KEY (user_name) REFERENCES users(name) ON UPDATE CASCADE ON DELETE RESTRICT;
```
Post Votes
```mysql
CREATE TABLE post_votes (
  /* keys */
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,

  /* date */
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NOT NULL DEFAULT NOW(),
  deleted_at DATETIME DEFAULT NULL,

  /* body */
  upvoted SMALLINT NOT NULL DEFAULT 0,

  /* foreign keys */
  user_id INT UNSIGNED NOT NULL,
  post_id INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE post_votes
  ADD UNIQUE KEY uidx_post_vote (user_id, post_id),
  ADD KEY idx_post_votes_deleted_at (deleted_at),
  ADD FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  ADD FOREIGN KEY (post_id) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE RESTRICT;
```
**Config** 
```yaml
version: "1"
packages: 
        - name: "db"
          path: "mysql/db"
          queries: "./mysql/query/"
          schema: "./mysql/schema/"
          engine: "mysql"
          emit_json_tags: true
          emit_prepared_queries: false
          emit_interface: true
          emit_exact_table_names: false
          emit_empty_slices: true
```
Maybe i'm not doing this right. Atleast i hope that this is the Problem.
