### ISSUE TITLE
Can't use type from the same package

### ISSUE THREAD

**Issue by maratori** [kyleconroy/sqlc#819]
Let's say I have following schema.

```sql
CREATE TABLE books (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR NOT NULL,
    params JSONB NOT NULL
);
```

And I want to use following type for `params` column:

```go
type BookParams struct {
	Foo string `json:"foo,omitempty"`
	Bar *int   `json:"bar,omitempty"`
}

func (p BookParams) Value() (driver.Value, error) {
	return json.Marshal(p)
}

func (p *BookParams) Scan(src interface{}) error {
	var source []byte
	switch t := src.(type) {
	case string:
		source = []byte(t)
	case []byte:
		source = t
	case nil:
		return nil
	default:
		return errors.Errorf("incompatible data type %T", src)
	}
	if len(source) == 0 {
		return nil
	}
	return json.Unmarshal(source, p)
}
```

I'd like to place `BookParams` type in the **same** package as code, generated by `sqlc`.
So I use following config:

```yml
version: "1"
packages:
  - name: "db"
    path: "./db"
    queries: "./db/queries.sql"
    schema: "./db/migrations/"
overrides:
  - column: "books.params"
    go_type: "BooksParams"
```

However it isn't possible because of error:
```
error parsing sqlc.yaml: Package override `go_type` specifier "BookParams" is not a Go basic type e.g. 'string'
```

The only way it works is to place type in the **different** package and to define full path, for example:
```yml
  - column: "books.params"
    go_type: "my.module/db/dbtype.BooksParams"
```

**Comment by kyleconroy** [comment]
@maratori This was actually fixed in https://github.com/kyleconroy/sqlc/issues/785, but I haven't updated the documentation in the README. You need to change how you're using the `go_type` value in the override. Also note that your example had a typo `/s/BooksParams/BookParams`.

```
# sqlc.yaml
version: "1"
packages:
  - name: "db"
    path: "db"
    queries: "db/queries.sql"
    schema: "db/schema.sql"
overrides:
  - column: "books.params"
    go_type:
      type: "BookParams"
```

Here's the rest of the working code:

```bash
$ tree .
.
├── db
│   ├── db.go
│   ├── models.go
│   ├── params.go
│   ├── queries.sql
│   └── schema.sql
└── sqlc.yaml
```

```sql
-- db/schema.sql

CREATE TABLE books (
    id UUID NOT NULL PRIMARY KEY,
    title VARCHAR NOT NULL,
    params JSONB NOT NULL
);
```

```sql
-- db/queries.sql

--name: ListBooks :many
SELECT * FROM books;
```

```go
// db/params.go

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

type BookParams struct {
	Foo string `json:"foo,omitempty"`
	Bar *int   `json:"bar,omitempty"`
}

func (p BookParams) Value() (driver.Value, error) {
	return json.Marshal(p)
}

func (p *BookParams) Scan(src interface{}) error {
	var source []byte
	switch t := src.(type) {
	case string:
		source = []byte(t)
	case []byte:
		source = t
	case nil:
		return nil
	default:
		return fmt.Errorf("incompatible data type %T", src)
	}
	if len(source) == 0 {
		return nil
	}
	return json.Unmarshal(source, p)
}
```

The following works on my machine:

```bash
$ sqlc generate
$ go build ./...
```
